// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
import TypedAPI

extension Paths {
    public static var pets: Pets {
        Pets(path: "/pets")
    }

    public struct Pets {
        /// Path: `/pets`
        public let path: String

        public func post(_ body: multiple_success_responses.Pet) -> Request<multiple_success_responses.Pet, PostError> {
            Request(path: path, method: "POST", body: body, id: "createPet")
        }

        public enum PostError: RequestError {
            case conflict(multiple_success_responses.Error)
            case unhandled(any Swift.Error)

            public static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
                switch statusCode {
                case 409: return .conflict(try decoder.decode(multiple_success_responses.Error.self, from: data))
                default: return .unhandled(APIError.unacceptableStatusCode(statusCode))
                }
            }

            public var statusCode: Int? {
                switch self {
                case .conflict: return 409
                case .unhandled(let error): return (error as? APIError)?.statusCode
                }
            }

            public var underlyingError: (any Swift.Error)? {
                switch self {
                case .unhandled(let error): return error
                default: return nil
                }
            }
        }
    }
}
