// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation

public struct Error: Codable, Sendable {
    public var message: String

    public init(message: String) {
        self.message = message
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.message = try values.decode(String.self, forKey: "message")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(message, forKey: "message")
    }
}
