// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
@preconcurrency import NaiveDate

public struct Dog: Codable, Sendable {
	public var className: String
	public var color: String?
	public var breed: Breed?
	public var image: Image?

	public enum Breed: String, Codable, CaseIterable, Sendable {
		case large = "Large"
		case medium = "Medium"
		case small = "Small"
	}

	public init(className: String, color: String? = nil, breed: Breed? = nil, image: Image? = nil) {
		self.className = className
		self.color = color
		self.breed = breed
		self.image = image
	}

	public init(from decoder: Decoder) throws {
		let values = try decoder.container(keyedBy: StringCodingKey.self)
		self.className = try values.decode(String.self, forKey: "className")
		self.color = values.contains("color") ? Optional.some(try values.decode(String.self, forKey: "color")) : nil
		self.breed = values.contains("breed") ? Optional.some(try values.decode(Breed.self, forKey: "breed")) : nil
		self.image = values.contains("image") ? Optional.some(try values.decode(Image.self, forKey: "image")) : nil
	}

	public func encode(to encoder: Encoder) throws {
		var values = encoder.container(keyedBy: StringCodingKey.self)
		try values.encode(className, forKey: "className")
		try values.encodeIfPresent(color, forKey: "color")
		try values.encodeIfPresent(breed, forKey: "breed")
		try values.encodeIfPresent(image, forKey: "image")
	}
}
