// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
import NaiveDate

public struct NumberOnly: Codable, Sendable {
	public var justNumber: Double?

	public init(justNumber: Double? = nil) {
		self.justNumber = justNumber
	}

	public init(from decoder: Decoder) throws {
		let values = try decoder.container(keyedBy: StringCodingKey.self)
		self.justNumber = try values.decodeIfPresent(Double.self, forKey: "JustNumber")
	}

	public func encode(to encoder: Encoder) throws {
		var values = encoder.container(keyedBy: StringCodingKey.self)
		try values.encodeIfPresent(justNumber, forKey: "JustNumber")
	}
}
