// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
import NaiveDate

public enum OuterEnum: String, Codable, CaseIterable {
	case placed
	case approved
	case delivered
}
