// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate
import HTTPHeaders
import TypedAPI
import URLQueryEncoder

extension Paths.Store.Order {
	public func orderID(_ orderID: Int) -> WithOrder {
		WithOrder(path: "\(path)/order-\(orderID)")
	}

	public struct WithOrder {
		/// Path: `/store/order/order-{order_id}`
		public let path: String

		/// Find purchase order by ID
		///
		/// For valid response try integer IDs with value <= 5 or > 10. Other values will generated exceptions
		public var get: Request<edgecases_tabs.Order, GetError> {
			Request(path: path, method: "GET", id: "getOrderById")
		}

		public enum GetError: RequestError {
			case badRequest
			case notFound
			case unhandled(any Swift.Error)

			public static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
				switch statusCode {
				case 400: return .badRequest
				case 404: return .notFound
				default: return .unhandled(APIError.unacceptableStatusCode(statusCode))
				}
			}
		}

		/// Delete purchase order by ID
		///
		/// For valid response try integer IDs with value < 1000. Anything above 1000 or nonintegers will generate API errors
		public var delete: Request<Void, DeleteError> {
			Request(path: path, method: "DELETE", id: "deleteOrder")
		}

		public enum DeleteError: RequestError {
			case badRequest
			case notFound
			case unhandled(any Swift.Error)

			public static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
				switch statusCode {
				case 400: return .badRequest
				case 404: return .notFound
				default: return .unhandled(APIError.unacceptableStatusCode(statusCode))
				}
			}
		}
	}
}
