// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
import NaiveDate
import HTTPHeaders
import TypedAPI
import URLQueryEncoder

extension Paths.Store.Order {
    func orderID(_ orderID: Int64) -> WithOrder {
        WithOrder(path: "\(path)/order-\(orderID)")
    }

    struct WithOrder {
        /// Path: `/store/order/order-{order_id}`
        let path: String

        /// Find purchase order by ID
        ///
        /// For valid response try integer IDs with value <= 5 or > 10. Other values will generated exceptions
        var get: Request<edgecases_change_access_control.Order, GetError> {
            Request(path: path, method: "GET", id: "getOrderById")
        }

        enum GetError: RequestError {
            case badRequest
            case notFound
            case unhandled(any Swift.Error)

            static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
                switch statusCode {
                case 400: return .badRequest
                case 404: return .notFound
                default: return .unhandled(APIError.unacceptableStatusCode(statusCode))
                }
            }

            var statusCode: Int? {
                switch self {
                case .badRequest: return 400
                case .notFound: return 404
                case .unhandled(let error): return (error as? APIError)?.statusCode
                }
            }

            var underlyingError: (any Swift.Error)? {
                switch self {
                case .unhandled(let error): return error
                default: return nil
                }
            }
        }

        /// Delete purchase order by ID
        ///
        /// For valid response try integer IDs with value < 1000. Anything above 1000 or nonintegers will generate API errors
        var delete: Request<Void, DeleteError> {
            Request(path: path, method: "DELETE", id: "deleteOrder")
        }

        enum DeleteError: RequestError {
            case badRequest
            case notFound
            case unhandled(any Swift.Error)

            static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
                switch statusCode {
                case 400: return .badRequest
                case 404: return .notFound
                default: return .unhandled(APIError.unacceptableStatusCode(statusCode))
                }
            }

            var statusCode: Int? {
                switch self {
                case .badRequest: return 400
                case .notFound: return 404
                case .unhandled(let error): return (error as? APIError)?.statusCode
                }
            }

            var underlyingError: (any Swift.Error)? {
                switch self {
                case .unhandled(let error): return error
                default: return nil
                }
            }
        }
    }
}
