// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
@preconcurrency import NaiveDate

public struct ArrayTest: Codable, Sendable {
    public var arrayOfString: [String]?
    public var arrayArrayOfInteger: [[Int]]?
    public var arrayArrayOfModel: [[ReadOnlyFirst]]?

    public init(arrayOfString: [String]? = nil, arrayArrayOfInteger: [[Int]]? = nil, arrayArrayOfModel: [[ReadOnlyFirst]]? = nil) {
        self.arrayOfString = arrayOfString
        self.arrayArrayOfInteger = arrayArrayOfInteger
        self.arrayArrayOfModel = arrayArrayOfModel
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.arrayOfString = values.contains("array_of_string") ? Optional.some(try values.decode([String].self, forKey: "array_of_string")) : nil
        self.arrayArrayOfInteger = values.contains("array_array_of_integer") ? Optional.some(try values.decode([[Int]].self, forKey: "array_array_of_integer")) : nil
        self.arrayArrayOfModel = values.contains("array_array_of_model") ? Optional.some(try values.decode([[ReadOnlyFirst]].self, forKey: "array_array_of_model")) : nil
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(arrayOfString, forKey: "array_of_string")
        try values.encodeIfPresent(arrayArrayOfInteger, forKey: "array_array_of_integer")
        try values.encodeIfPresent(arrayArrayOfModel, forKey: "array_array_of_model")
    }
}
