// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
@preconcurrency import NaiveDate

public struct MixedPropertiesAndAdditionalPropertiesClass: Codable, Sendable {
    public var uuid: UUID?
    public var dateTime: AnyJSON?
    public var map: [String: Animal]?

    public init(uuid: UUID? = nil, dateTime: AnyJSON? = nil, map: [String: Animal]? = nil) {
        self.uuid = uuid
        self.dateTime = dateTime
        self.map = map
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.uuid = values.contains("uuid") ? Optional.some(try values.decode(UUID.self, forKey: "uuid")) : nil
        self.dateTime = values.contains("dateTime") ? Optional.some(try values.decode(AnyJSON.self, forKey: "dateTime")) : nil
        self.map = values.contains("map") ? Optional.some(try values.decode([String: Animal].self, forKey: "map")) : nil
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(uuid, forKey: "uuid")
        try values.encodeIfPresent(dateTime, forKey: "dateTime")
        try values.encodeIfPresent(map, forKey: "map")
    }
}
