// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
@preconcurrency import NaiveDate

public struct Order: Codable, Sendable {
    public var id: Int?
    public var petID: Int?
    public var quantity: Double?
    public var shipDate: AnyJSON?
    /// Order Status
    public var status: Status?
    public var isComplete: Bool

    /// Order Status
    public enum Status: String, Codable, CaseIterable, Sendable {
        case placed
        case approved
        case delivered
    }

    public init(id: Int? = nil, petID: Int? = nil, quantity: Double? = nil, shipDate: AnyJSON? = nil, status: Status? = nil, isComplete: Bool? = nil) {
        self.id = id
        self.petID = petID
        self.quantity = quantity
        self.shipDate = shipDate
        self.status = status
        self.isComplete = isComplete ?? false
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = values.contains("id") ? Optional.some(try values.decode(Int.self, forKey: "id")) : nil
        self.petID = values.contains("petId") ? Optional.some(try values.decode(Int.self, forKey: "petId")) : nil
        self.quantity = values.contains("quantity") ? Optional.some(try values.decode(Double.self, forKey: "quantity")) : nil
        self.shipDate = values.contains("shipDate") ? Optional.some(try values.decode(AnyJSON.self, forKey: "shipDate")) : nil
        self.status = values.contains("status") ? Optional.some(try values.decode(Status.self, forKey: "status")) : nil
        self.isComplete = values.contains("complete") ? try values.decode(Bool.self, forKey: "complete") : false
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(id, forKey: "id")
        try values.encodeIfPresent(petID, forKey: "petId")
        try values.encodeIfPresent(quantity, forKey: "quantity")
        try values.encodeIfPresent(shipDate, forKey: "shipDate")
        try values.encodeIfPresent(status, forKey: "status")
        try values.encodeIfPresent(isComplete, forKey: "complete")
    }
}
