// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
@preconcurrency import NaiveDate

public struct User: Codable, Sendable {
    public var id: Int?
    public var username: String?
    public var firstName: String?
    public var lastName: String?
    public var email: String?
    public var password: String?
    public var phone: String?
    /// User Status
    public var userStatus: Double?

    public init(id: Int? = nil, username: String? = nil, firstName: String? = nil, lastName: String? = nil, email: String? = nil, password: String? = nil, phone: String? = nil, userStatus: Double? = nil) {
        self.id = id
        self.username = username
        self.firstName = firstName
        self.lastName = lastName
        self.email = email
        self.password = password
        self.phone = phone
        self.userStatus = userStatus
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = values.contains("id") ? Optional.some(try values.decode(Int.self, forKey: "id")) : nil
        self.username = values.contains("username") ? Optional.some(try values.decode(String.self, forKey: "username")) : nil
        self.firstName = values.contains("firstName") ? Optional.some(try values.decode(String.self, forKey: "firstName")) : nil
        self.lastName = values.contains("lastName") ? Optional.some(try values.decode(String.self, forKey: "lastName")) : nil
        self.email = values.contains("email") ? Optional.some(try values.decode(String.self, forKey: "email")) : nil
        self.password = values.contains("password") ? Optional.some(try values.decode(String.self, forKey: "password")) : nil
        self.phone = values.contains("phone") ? Optional.some(try values.decode(String.self, forKey: "phone")) : nil
        self.userStatus = values.contains("userStatus") ? Optional.some(try values.decode(Double.self, forKey: "userStatus")) : nil
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(id, forKey: "id")
        try values.encodeIfPresent(username, forKey: "username")
        try values.encodeIfPresent(firstName, forKey: "firstName")
        try values.encodeIfPresent(lastName, forKey: "lastName")
        try values.encodeIfPresent(email, forKey: "email")
        try values.encodeIfPresent(password, forKey: "password")
        try values.encodeIfPresent(phone, forKey: "phone")
        try values.encodeIfPresent(userStatus, forKey: "userStatus")
    }
}
