// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import TypedAPI
import URLQueryEncoder

extension Paths {
    public static var form: Form {
        Form(path: "/form")
    }

    public struct Form {
        /// Path: `/form`
        public let path: String
    }
}
