// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
import TypedAPI

extension Paths {
    public static var container: Container {
        Container(path: "/container")
    }

    public struct Container {
        /// Path: `/container`
        public let path: String

        public var get: Request<discriminator.Container, DefaultRequestError> {
            Request(path: path, method: "GET")
        }
    }
}
