// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import HTTPHeaders
import TypedAPI
import URLQueryEncoder

extension Paths.Pets {
    public func petID(_ petID: String) -> WithPetID {
        WithPetID(path: "\(path)/\(petID)")
    }

    public struct WithPetID {
        /// Path: `/pets/{petId}`
        public let path: String

        /// Info for a specific pet
        public var get: Request<petstore_default.Pet, GetError> {
            Request(path: path, method: "GET", id: "showPetById")
        }

        public enum GetError: RequestError {
            case `default`(statusCode: Int, petstore_default.Error)
            case unhandled(any Swift.Error)

            public static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
                switch statusCode {
                default: return .`default`(statusCode: statusCode, try decoder.decode(petstore_default.Error.self, from: data))
                }
            }
        }
    }
}
