// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation

public struct ContainerA: Codable, Sendable {
    public var a: String?

    public init(a: String? = nil) {
        self.a = a
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.a = try values.decodeIfPresent(String.self, forKey: "a")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(a, forKey: "a")
    }
}
