// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
import HTTPHeaders
import TypedAPI
import URLQueryEncoder

public enum Paths {}

extension Paths {
    public static var pets: Pets {
        Pets(path: "/pets")
    }

    public struct Pets {
        /// Path: `/pets`
        public let path: String

        /// List all pets
        public func get(limit: Int32? = nil) -> Request<[petstore_merge_sources.Pet], GetError> {
            Request(path: path, method: "GET", query: makeGetQuery(limit), id: "listPets")
        }

        public enum GetError: RequestError {
            case `default`(statusCode: Int, petstore_merge_sources.Error)
            case unhandled(any Swift.Error)

            public static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
                switch statusCode {
                default: return .`default`(statusCode: statusCode, try decoder.decode(petstore_merge_sources.Error.self, from: data))
                }
            }

            public var statusCode: Int? {
                switch self {
                case .`default`(let statusCode, _): return statusCode
                case .unhandled(let error): return (error as? APIError)?.statusCode
                }
            }

            public var underlyingError: (any Swift.Error)? {
                switch self {
                case .unhandled(let error): return error
                default: return nil
                }
            }
        }

        public enum GetResponseHeaders {
            /// A link to the next page of responses
            public static let next = HTTPHeader<String>(field: "x-next")
        }

        private func makeGetQuery(_ limit: Int32?) -> [(String, String?)] {
            let encoder = URLQueryEncoder()
            encoder.encode(limit, forKey: "limit")
            return encoder.items
        }

        /// Create a pet
        public var post: Request<Void, PostError> {
            Request(path: path, method: "POST", id: "createPets")
        }

        public enum PostError: RequestError {
            case `default`(statusCode: Int, petstore_merge_sources.Error)
            case unhandled(any Swift.Error)

            public static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
                switch statusCode {
                default: return .`default`(statusCode: statusCode, try decoder.decode(petstore_merge_sources.Error.self, from: data))
                }
            }

            public var statusCode: Int? {
                switch self {
                case .`default`(let statusCode, _): return statusCode
                case .unhandled(let error): return (error as? APIError)?.statusCode
                }
            }

            public var underlyingError: (any Swift.Error)? {
                switch self {
                case .unhandled(let error): return error
                default: return nil
                }
            }
        }
    }
}

extension Paths.Pets {
    public func petID(_ petID: String) -> WithPetID {
        WithPetID(path: "\(path)/\(petID)")
    }

    public struct WithPetID {
        /// Path: `/pets/{petId}`
        public let path: String

        /// Info for a specific pet
        public var get: Request<petstore_merge_sources.Pet, GetError> {
            Request(path: path, method: "GET", id: "showPetById")
        }

        public enum GetError: RequestError {
            case `default`(statusCode: Int, petstore_merge_sources.Error)
            case unhandled(any Swift.Error)

            public static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
                switch statusCode {
                default: return .`default`(statusCode: statusCode, try decoder.decode(petstore_merge_sources.Error.self, from: data))
                }
            }

            public var statusCode: Int? {
                switch self {
                case .`default`(let statusCode, _): return statusCode
                case .unhandled(let error): return (error as? APIError)?.statusCode
                }
            }

            public var underlyingError: (any Swift.Error)? {
                switch self {
                case .unhandled(let error): return error
                default: return nil
                }
            }
        }
    }
}
