// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
import HTTPHeaders
import TypedAPI
import URLQueryEncoder

extension Paths.Gitignore.Templates {
    public func name(_ name: String) -> WithName {
        WithName(path: "\(path)/\(name)")
    }

    public struct WithName {
        /// Path: `/gitignore/templates/{name}`
        public let path: String

        /// Get a gitignore template
        ///
        /// The API also allows fetching the source of a single template.
        /// Use the raw [media type](https://docs.github.com/rest/overview/media-types/) to get the raw contents.
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/gitignore#get-a-gitignore-template)
        public var get: Request<OctoKit.GitignoreTemplate, GetError> {
            Request(path: path, method: "GET", id: "gitignore/get-template")
        }

        public enum GetError: RequestError {
            case notModified
            case unhandled(any Swift.Error)

            public static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
                switch statusCode {
                case 304: return .notModified
                default: return .unhandled(APIError.unacceptableStatusCode(statusCode))
                }
            }
        }
    }
}
