// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import HTTPHeaders
import URLQueryEncoder

extension Paths.Projects.Columns {
    public func columnID(_ columnID: Int) -> WithColumnID {
        WithColumnID(path: "\(path)/\(columnID)")
    }

    public struct WithColumnID {
        /// Path: `/projects/columns/{column_id}`
        public let path: String

        /// Get a project column
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/projects#get-a-project-column)
        public var get: Request<OctoKit.ProjectColumn> {
            get throws(GetError) {
                Request(path: path, method: "GET", id: "projects/get-column")
            }
        }

        public enum GetError: Error {
            case notModified
            case forbidden(OctoKit.BasicError)
            case notFound(OctoKit.BasicError)
            case unauthorized(OctoKit.BasicError)
        }

        /// Update an existing project column
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/projects#update-a-project-column)
        public func patch(name: String) throws(PatchError) -> Request<OctoKit.ProjectColumn> {
            Request(path: path, method: "PATCH", body: ["name": name], id: "projects/update-column")
        }

        public enum PatchError: Error {
            case notModified
            case forbidden(OctoKit.BasicError)
            case unauthorized(OctoKit.BasicError)
        }

        /// Delete a project column
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/projects#delete-a-project-column)
        public var delete: Request<Void> {
            get throws(DeleteError) {
                Request(path: path, method: "DELETE", id: "projects/delete-column")
            }
        }

        public enum DeleteError: Error {
            case notModified
            case forbidden(OctoKit.BasicError)
            case unauthorized(OctoKit.BasicError)
        }
    }
}
