// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import HTTPHeaders
import TypedAPI
import URLQueryEncoder

extension Paths.Repos.WithOwner.WithRepo.Issues {
    public var comments: Comments {
        Comments(path: path + "/comments")
    }

    public struct Comments {
        /// Path: `/repos/{owner}/{repo}/issues/comments`
        public let path: String

        /// List issue comments for a repository
        ///
        /// By default, Issue Comments are ordered by ascending ID.
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/issues#list-issue-comments-for-a-repository)
        public func get(parameters: GetParameters? = nil) -> Request<[OctoKit.IssueComment], GetError> {
            Request(path: path, method: "GET", query: parameters?.asQuery, id: "issues/list-comments-for-repo")
        }

        public enum GetError: RequestError {
            case unprocessableEntity(OctoKit.ValidationError)
            case notFound(OctoKit.BasicError)
            case unhandled(any Swift.Error)

            public static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
                switch statusCode {
                case 422: return .unprocessableEntity(try decoder.decode(OctoKit.ValidationError.self, from: data))
                case 404: return .notFound(try decoder.decode(OctoKit.BasicError.self, from: data))
                default: return .unhandled(APIError.unacceptableStatusCode(statusCode))
                }
            }
        }

        public enum GetResponseHeaders {
            public static let link = HTTPHeader<String>(field: "Link")
        }

        public struct GetParameters {
            public var sort: Sort?
            public var direction: Direction?
            public var since: Date?
            public var perPage: Int?
            public var page: Int?

            public enum Sort: String, Codable, CaseIterable {
                case created
                case updated
            }

            public enum Direction: String, Codable, CaseIterable {
                case asc
                case desc
            }

            public init(sort: Sort? = nil, direction: Direction? = nil, since: Date? = nil, perPage: Int? = nil, page: Int? = nil) {
                self.sort = sort
                self.direction = direction
                self.since = since
                self.perPage = perPage
                self.page = page
            }

            public var asQuery: [(String, String?)] {
                let encoder = URLQueryEncoder()
                encoder.encode(sort, forKey: "sort")
                encoder.encode(direction, forKey: "direction")
                encoder.encode(since, forKey: "since")
                encoder.encode(perPage, forKey: "per_page")
                encoder.encode(page, forKey: "page")
                return encoder.items
            }
        }
    }
}
