// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
import HTTPHeaders
import TypedAPI
import URLQueryEncoder

extension Paths.User.Codespaces.Secrets.WithSecretName.Repositories {
    public func repositoryID(_ repositoryID: Int) -> WithRepositoryID {
        WithRepositoryID(path: "\(path)/\(repositoryID)")
    }

    public struct WithRepositoryID {
        /// Path: `/user/codespaces/secrets/{secret_name}/repositories/{repository_id}`
        public let path: String

        /// Add a selected repository to a user secret
        ///
        /// Adds a repository to the selected repositories for a user's codespace secret.
        /// You must authenticate using an access token with the `user` or `read:user` scope to use this endpoint. User must have Codespaces access to use this endpoint.
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/codespaces#add-a-selected-repository-to-a-user-secret)
        public var put: Request<Void, PutError> {
            Request(path: path, method: "PUT", id: "codespaces/add-repository-for-secret-for-authenticated-user")
        }

        public enum PutError: RequestError {
            case unauthorized(OctoKit.BasicError)
            case forbidden(OctoKit.BasicError)
            case notFound(OctoKit.BasicError)
            case internalServerError(OctoKit.BasicError)
            case unhandled(any Swift.Error)

            public static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
                switch statusCode {
                case 401: return .unauthorized(try decoder.decode(OctoKit.BasicError.self, from: data))
                case 403: return .forbidden(try decoder.decode(OctoKit.BasicError.self, from: data))
                case 404: return .notFound(try decoder.decode(OctoKit.BasicError.self, from: data))
                case 500: return .internalServerError(try decoder.decode(OctoKit.BasicError.self, from: data))
                default: return .unhandled(APIError.unacceptableStatusCode(statusCode))
                }
            }
        }

        /// Remove a selected repository from a user secret
        ///
        /// Removes a repository from the selected repositories for a user's codespace secret.
        /// You must authenticate using an access token with the `user` or `read:user` scope to use this endpoint. User must have Codespaces access to use this endpoint.
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/codespaces#remove-a-selected-repository-from-a-user-secret)
        public var delete: Request<Void, DeleteError> {
            Request(path: path, method: "DELETE", id: "codespaces/remove-repository-for-secret-for-authenticated-user")
        }

        public enum DeleteError: RequestError {
            case unauthorized(OctoKit.BasicError)
            case forbidden(OctoKit.BasicError)
            case notFound(OctoKit.BasicError)
            case internalServerError(OctoKit.BasicError)
            case unhandled(any Swift.Error)

            public static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
                switch statusCode {
                case 401: return .unauthorized(try decoder.decode(OctoKit.BasicError.self, from: data))
                case 403: return .forbidden(try decoder.decode(OctoKit.BasicError.self, from: data))
                case 404: return .notFound(try decoder.decode(OctoKit.BasicError.self, from: data))
                case 500: return .internalServerError(try decoder.decode(OctoKit.BasicError.self, from: data))
                default: return .unhandled(APIError.unacceptableStatusCode(statusCode))
                }
            }
        }
    }
}
