// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
import HTTPHeaders
import TypedAPI
import URLQueryEncoder

extension Paths.Gists.WithGistID {
    public var star: Star {
        Star(path: path + "/star")
    }

    public struct Star {
        /// Path: `/gists/{gist_id}/star`
        public let path: String

        /// Check if a gist is starred
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/gists#check-if-a-gist-is-starred)
        public var get: Request<Void, GetError> {
            Request(path: path, method: "GET", id: "gists/check-is-starred")
        }

        public enum GetError: RequestError {
            case notFound
            case notModified
            case forbidden(OctoKit.BasicError)
            case unhandled(any Swift.Error)

            public static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
                switch statusCode {
                case 404: return .notFound
                case 304: return .notModified
                case 403: return .forbidden(try decoder.decode(OctoKit.BasicError.self, from: data))
                default: return .unhandled(APIError.unacceptableStatusCode(statusCode))
                }
            }
        }

        /// Star a gist
        ///
        /// Note that you'll need to set `Content-Length` to zero when calling out to this endpoint. For more information, see "[HTTP verbs](https://docs.github.com/rest/overview/resources-in-the-rest-api#http-verbs)."
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/gists#star-a-gist)
        public var put: Request<Void, PutError> {
            Request(path: path, method: "PUT", id: "gists/star")
        }

        public enum PutError: RequestError {
            case notFound(OctoKit.BasicError)
            case notModified
            case forbidden(OctoKit.BasicError)
            case unhandled(any Swift.Error)

            public static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
                switch statusCode {
                case 404: return .notFound(try decoder.decode(OctoKit.BasicError.self, from: data))
                case 304: return .notModified
                case 403: return .forbidden(try decoder.decode(OctoKit.BasicError.self, from: data))
                default: return .unhandled(APIError.unacceptableStatusCode(statusCode))
                }
            }
        }

        /// Unstar a gist
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/gists#unstar-a-gist)
        public var delete: Request<Void, DeleteError> {
            Request(path: path, method: "DELETE", id: "gists/unstar")
        }

        public enum DeleteError: RequestError {
            case notModified
            case notFound(OctoKit.BasicError)
            case forbidden(OctoKit.BasicError)
            case unhandled(any Swift.Error)

            public static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
                switch statusCode {
                case 304: return .notModified
                case 404: return .notFound(try decoder.decode(OctoKit.BasicError.self, from: data))
                case 403: return .forbidden(try decoder.decode(OctoKit.BasicError.self, from: data))
                default: return .unhandled(APIError.unacceptableStatusCode(statusCode))
                }
            }
        }
    }
}
