// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
import HTTPHeaders
import TypedAPI
import URLQueryEncoder

extension Paths.Orgs.WithOrg {
    public var installation: Installation {
        Installation(path: path + "/installation")
    }

    public struct Installation {
        /// Path: `/orgs/{org}/installation`
        public let path: String

        /// Get an organization installation for the authenticated app
        ///
        /// Enables an authenticated GitHub App to find the organization's installation information.
        /// 
        /// You must use a [JWT](https://docs.github.com/apps/building-github-apps/authenticating-with-github-apps/#authenticating-as-a-github-app) to access this endpoint.
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/apps#get-an-organization-installation-for-the-authenticated-app)
        public var get: Request<OctoKit.Installation, DefaultRequestError> {
            Request(path: path, method: "GET", id: "apps/get-org-installation")
        }
    }
}
