// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import HTTPHeaders
import TypedAPI
import URLQueryEncoder

extension Paths.Repos.WithOwner.WithRepo.CodeScanning.Sarifs {
    public func sarifID(_ sarifID: String) -> WithSarifID {
        WithSarifID(path: "\(path)/\(sarifID)")
    }

    public struct WithSarifID {
        /// Path: `/repos/{owner}/{repo}/code-scanning/sarifs/{sarif_id}`
        public let path: String

        /// Get information about a SARIF upload
        ///
        /// Gets information about a SARIF upload, including the status and the URL of the analysis that was uploaded so that you can retrieve details of the analysis. For more information, see "[Get a code scanning analysis for a repository](/rest/reference/code-scanning#get-a-code-scanning-analysis-for-a-repository)." You must use an access token with the `security_events` scope to use this endpoint with private repos, the `public_repo` scope also grants permission to read security events on public repos only. GitHub Apps must have the `security_events` read permission to use this endpoint.
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/code-scanning#list-recent-code-scanning-analyses-for-a-repository)
        public var get: Request<OctoKit.CodeScanningSarifsStatus, GetError> {
            Request(path: path, method: "GET", id: "code-scanning/get-sarif")
        }

        public enum GetError: RequestError {
            case forbidden(OctoKit.BasicError)
            case notFound
            case serviceUnavailable(GetServiceUnavailableBody)
            case unhandled(any Swift.Error)

            public static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
                switch statusCode {
                case 403: return .forbidden(try decoder.decode(OctoKit.BasicError.self, from: data))
                case 404: return .notFound
                case 503: return .serviceUnavailable(try decoder.decode(GetServiceUnavailableBody.self, from: data))
                default: return .unhandled(APIError.unacceptableStatusCode(statusCode))
                }
            }
        }

        public struct GetServiceUnavailableBody: Decodable {
            public var code: String?
            public var message: String?
            public var documentationURL: String?

            public init(code: String? = nil, message: String? = nil, documentationURL: String? = nil) {
                self.code = code
                self.message = message
                self.documentationURL = documentationURL
            }

            public init(from decoder: Decoder) throws {
                let values = try decoder.container(keyedBy: StringCodingKey.self)
                self.code = try values.decodeIfPresent(String.self, forKey: "code")
                self.message = try values.decodeIfPresent(String.self, forKey: "message")
                self.documentationURL = try values.decodeIfPresent(String.self, forKey: "documentation_url")
            }
        }
    }
}
