// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import HTTPHeaders
import TypedAPI
import URLQueryEncoder

extension Paths.User.Packages.WithPackageType.WithPackageName {
    public var versions: Versions {
        Versions(path: path + "/versions")
    }

    public struct Versions {
        /// Path: `/user/packages/{package_type}/{package_name}/versions`
        public let path: String

        /// Get all package versions for a package owned by the authenticated user
        ///
        /// Returns all package versions for a package owned by the authenticated user.
        /// 
        /// To use this endpoint, you must authenticate using an access token with the `packages:read` scope.
        /// If `package_type` is not `container`, your token must also include the `repo` scope.
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/packages#get-all-package-versions-for-a-package-owned-by-the-authenticated-user)
        public func get(parameters: GetParameters? = nil) -> Request<[OctoKit.PackageVersion], GetError> {
            Request(path: path, method: "GET", query: parameters?.asQuery, id: "packages/get-all-package-versions-for-package-owned-by-authenticated-user")
        }

        public enum GetError: RequestError {
            case notFound(OctoKit.BasicError)
            case forbidden(OctoKit.BasicError)
            case unauthorized(OctoKit.BasicError)
            case unhandled(any Swift.Error)

            public static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
                switch statusCode {
                case 404: return .notFound(try decoder.decode(OctoKit.BasicError.self, from: data))
                case 403: return .forbidden(try decoder.decode(OctoKit.BasicError.self, from: data))
                case 401: return .unauthorized(try decoder.decode(OctoKit.BasicError.self, from: data))
                default: return .unhandled(APIError.unacceptableStatusCode(statusCode))
                }
            }
        }

        public struct GetParameters {
            public var page: Int?
            public var perPage: Int?
            public var state: State?

            public enum State: String, Codable, CaseIterable {
                case active
                case deleted
            }

            public init(page: Int? = nil, perPage: Int? = nil, state: State? = nil) {
                self.page = page
                self.perPage = perPage
                self.state = state
            }

            public var asQuery: [(String, String?)] {
                let encoder = URLQueryEncoder()
                encoder.encode(page, forKey: "page")
                encoder.encode(perPage, forKey: "per_page")
                encoder.encode(state, forKey: "state")
                return encoder.items
            }
        }
    }
}
