// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import HTTPHeaders
import TypedAPI
import URLQueryEncoder

extension Paths {
    public static var codesOfConduct: CodesOfConduct {
        CodesOfConduct(path: "/codes_of_conduct")
    }

    public struct CodesOfConduct {
        /// Path: `/codes_of_conduct`
        public let path: String

        /// Get all codes of conduct
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/codes-of-conduct#get-all-codes-of-conduct)
        public var get: Request<[OctoKit.CodeOfConduct], GetError> {
            Request(path: path, method: "GET", id: "codes-of-conduct/get-all-codes-of-conduct")
        }

        public enum GetError: RequestError {
            case notModified
            case unhandled(any Swift.Error)

            public static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
                switch statusCode {
                case 304: return .notModified
                default: return .unhandled(APIError.unacceptableStatusCode(statusCode))
                }
            }
        }
    }
}
