// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
import HTTPHeaders
import TypedAPI
import URLQueryEncoder

extension Paths {
    public static var applications: Applications {
        Applications(path: "/applications")
    }

    public struct Applications {
        /// Path: `/applications`
        public let path: String
    }
}
