// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
import HTTPHeaders
import TypedAPI
import URLQueryEncoder

extension Paths.Authorizations {
    public var clients: Clients {
        Clients(path: path + "/clients")
    }

    public struct Clients {
        /// Path: `/authorizations/clients`
        public let path: String
    }
}
