// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import HTTPHeaders
import TypedAPI
import URLQueryEncoder

extension Paths.Repos.WithOwner.WithRepo.Git.Trees {
    public func treeSha(_ treeSha: String) -> WithTreeSha {
        WithTreeSha(path: "\(path)/\(treeSha)")
    }

    public struct WithTreeSha {
        /// Path: `/repos/{owner}/{repo}/git/trees/{tree_sha}`
        public let path: String

        /// Get a tree
        ///
        /// Returns a single tree using the SHA1 value for that tree.
        /// 
        /// If `truncated` is `true` in the response then the number of items in the `tree` array exceeded our maximum limit. If you need to fetch more items, use the non-recursive method of fetching trees, and fetch one sub-tree at a time.
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/git#get-a-tree)
        public func get(recursive: String? = nil) -> Request<OctoKit.GitTree, GetError> {
            Request(path: path, method: "GET", query: makeGetQuery(recursive), id: "git/get-tree")
        }

        public enum GetError: RequestError {
            case unprocessableEntity(OctoKit.ValidationError)
            case notFound(OctoKit.BasicError)
            case unhandled(any Swift.Error)

            public static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
                switch statusCode {
                case 422: return .unprocessableEntity(try decoder.decode(OctoKit.ValidationError.self, from: data))
                case 404: return .notFound(try decoder.decode(OctoKit.BasicError.self, from: data))
                default: return .unhandled(APIError.unacceptableStatusCode(statusCode))
                }
            }
        }

        private func makeGetQuery(_ recursive: String?) -> [(String, String?)] {
            let encoder = URLQueryEncoder()
            encoder.encode(recursive, forKey: "recursive")
            return encoder.items
        }
    }
}
