// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
import HTTPHeaders
import TypedAPI
import URLQueryEncoder

extension Paths {
    public static var installation: Installation {
        Installation(path: "/installation")
    }

    public struct Installation {
        /// Path: `/installation`
        public let path: String
    }
}
