// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import HTTPHeaders
import TypedAPI
import URLQueryEncoder

extension Paths {
    public static var gitignore: Gitignore {
        Gitignore(path: "/gitignore")
    }

    public struct Gitignore {
        /// Path: `/gitignore`
        public let path: String
    }
}
