// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
import HTTPHeaders
import TypedAPI
import URLQueryEncoder

extension Paths.Orgs.WithOrg.Hooks.WithHookID {
    public var pings: Pings {
        Pings(path: path + "/pings")
    }

    public struct Pings {
        /// Path: `/orgs/{org}/hooks/{hook_id}/pings`
        public let path: String

        /// Ping an organization webhook
        ///
        /// This will trigger a [ping event](https://docs.github.com/webhooks/#ping-event) to be sent to the hook.
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/orgs#ping-an-organization-webhook)
        public var post: Request<Void, PostError> {
            Request(path: path, method: "POST", id: "orgs/ping-webhook")
        }

        public enum PostError: RequestError {
            case notFound(OctoKit.BasicError)
            case unhandled(any Swift.Error)

            public static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
                switch statusCode {
                case 404: return .notFound(try decoder.decode(OctoKit.BasicError.self, from: data))
                default: return .unhandled(APIError.unacceptableStatusCode(statusCode))
                }
            }
        }
    }
}
