// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
import HTTPHeaders
import TypedAPI
import URLQueryEncoder

extension Paths.Repos.WithOwner.WithRepo {
    public var mergeUpstream: MergeUpstream {
        MergeUpstream(path: path + "/merge-upstream")
    }

    public struct MergeUpstream {
        /// Path: `/repos/{owner}/{repo}/merge-upstream`
        public let path: String

        /// Sync a fork branch with the upstream repository
        ///
        /// Sync a branch of a forked repository to keep it up-to-date with the upstream repository.
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/repos#sync-a-fork-branch-with-the-upstream-repository)
        public func post(branch: String) -> Request<OctoKit.MergedUpstream, PostError> {
            Request(path: path, method: "POST", body: ["branch": branch], id: "repos/merge-upstream")
        }

        public enum PostError: RequestError {
            case conflict
            case unprocessableEntity
            case unhandled(any Swift.Error)

            public static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
                switch statusCode {
                case 409: return .conflict
                case 422: return .unprocessableEntity
                default: return .unhandled(APIError.unacceptableStatusCode(statusCode))
                }
            }
        }
    }
}
