// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
import HTTPHeaders
import TypedAPI
import URLQueryEncoder

extension Paths.User.Codespaces {
    public func codespaceName(_ codespaceName: String) -> WithCodespaceName {
        WithCodespaceName(path: "\(path)/\(codespaceName)")
    }

    public struct WithCodespaceName {
        /// Path: `/user/codespaces/{codespace_name}`
        public let path: String

        /// Get a codespace for the authenticated user
        ///
        /// Gets information about a user's codespace.
        /// 
        /// You must authenticate using an access token with the `codespace` scope to use this endpoint.
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/codespaces#get-a-codespace-for-the-authenticated-user)
        public var get: Request<OctoKit.Codespace, GetError> {
            Request(path: path, method: "GET", id: "codespaces/get-for-authenticated-user")
        }

        public enum GetError: RequestError {
            case notModified
            case internalServerError(OctoKit.BasicError)
            case unauthorized(OctoKit.BasicError)
            case forbidden(OctoKit.BasicError)
            case notFound(OctoKit.BasicError)
            case unhandled(any Swift.Error)

            public static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
                switch statusCode {
                case 304: return .notModified
                case 500: return .internalServerError(try decoder.decode(OctoKit.BasicError.self, from: data))
                case 401: return .unauthorized(try decoder.decode(OctoKit.BasicError.self, from: data))
                case 403: return .forbidden(try decoder.decode(OctoKit.BasicError.self, from: data))
                case 404: return .notFound(try decoder.decode(OctoKit.BasicError.self, from: data))
                default: return .unhandled(APIError.unacceptableStatusCode(statusCode))
                }
            }
        }

        /// Update a codespace for the authenticated user
        ///
        /// Updates a codespace owned by the authenticated user. Currently only the codespace's machine type can be modified using this endpoint.
        /// 
        /// Once you specify a new machine type it will be applied the next time your codespace is started.
        /// 
        /// You must authenticate using an access token with the `codespace` scope to use this endpoint.
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/codespaces#update-a-codespace-for-the-authenticated-user)
        public func patch(machine: String? = nil) -> Request<OctoKit.Codespace, PatchError> {
            Request(path: path, method: "PATCH", body: ["machine": machine], id: "codespaces/update-for-authenticated-user")
        }

        public enum PatchError: RequestError {
            case unauthorized(OctoKit.BasicError)
            case forbidden(OctoKit.BasicError)
            case notFound(OctoKit.BasicError)
            case unhandled(any Swift.Error)

            public static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
                switch statusCode {
                case 401: return .unauthorized(try decoder.decode(OctoKit.BasicError.self, from: data))
                case 403: return .forbidden(try decoder.decode(OctoKit.BasicError.self, from: data))
                case 404: return .notFound(try decoder.decode(OctoKit.BasicError.self, from: data))
                default: return .unhandled(APIError.unacceptableStatusCode(statusCode))
                }
            }
        }

        /// Delete a codespace for the authenticated user
        ///
        /// Deletes a user's codespace.
        /// 
        /// You must authenticate using an access token with the `codespace` scope to use this endpoint.
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/codespaces#delete-a-codespace-for-the-authenticated-user)
        public var delete: Request<[String: AnyJSON], DeleteError> {
            Request(path: path, method: "DELETE", id: "codespaces/delete-for-authenticated-user")
        }

        public enum DeleteError: RequestError {
            case notModified
            case internalServerError(OctoKit.BasicError)
            case unauthorized(OctoKit.BasicError)
            case forbidden(OctoKit.BasicError)
            case notFound(OctoKit.BasicError)
            case unhandled(any Swift.Error)

            public static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
                switch statusCode {
                case 304: return .notModified
                case 500: return .internalServerError(try decoder.decode(OctoKit.BasicError.self, from: data))
                case 401: return .unauthorized(try decoder.decode(OctoKit.BasicError.self, from: data))
                case 403: return .forbidden(try decoder.decode(OctoKit.BasicError.self, from: data))
                case 404: return .notFound(try decoder.decode(OctoKit.BasicError.self, from: data))
                default: return .unhandled(APIError.unacceptableStatusCode(statusCode))
                }
            }
        }
    }
}
