// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
@preconcurrency import HTTPHeaders
import TypedAPI
import URLQueryEncoder

extension Paths {
    public static var networks: Networks {
        Networks(path: "/networks")
    }

    public struct Networks {
        /// Path: `/networks`
        public let path: String
    }
}
