// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
import HTTPHeaders
import TypedAPI
import URLQueryEncoder

extension Paths.Repos.WithTemplateOwner {
    public func templateRepo(_ templateRepo: String) -> WithTemplateRepo {
        WithTemplateRepo(path: "\(path)/\(templateRepo)")
    }

    public struct WithTemplateRepo {
        /// Path: `/repos/{template_owner}/{template_repo}`
        public let path: String
    }
}
