// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
@preconcurrency import HTTPHeaders
import TypedAPI
import URLQueryEncoder

extension Paths.Repos.WithOwner.WithRepo {
    public var lfs: Lfs {
        Lfs(path: path + "/lfs")
    }

    public struct Lfs {
        /// Path: `/repos/{owner}/{repo}/lfs`
        public let path: String

        /// Enable Git LFS for a repository
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/repos#enable-git-lfs-for-a-repository)
        public var put: Request<Void, PutError> {
            Request(path: path, method: "PUT", id: "repos/enable-lfs-for-repo")
        }

        public enum PutError: RequestError {
            case forbidden
            case unhandled(any Swift.Error)

            public static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
                switch statusCode {
                case 403: return .forbidden
                default: return .unhandled(APIError.unacceptableStatusCode(statusCode))
                }
            }

            public var statusCode: Int? {
                switch self {
                case .forbidden: return 403
                case .unhandled(let error): return (error as? APIError)?.statusCode
                }
            }

            public var underlyingError: (any Swift.Error)? {
                switch self {
                case .unhandled(let error): return error
                default: return nil
                }
            }
        }

        /// Disable Git LFS for a repository
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/repos#disable-git-lfs-for-a-repository)
        public var delete: Request<Void, DefaultRequestError> {
            Request(path: path, method: "DELETE", id: "repos/disable-lfs-for-repo")
        }
    }
}
