// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
import HTTPHeaders
import TypedAPI
import URLQueryEncoder

extension Paths.Repos.WithOwner.WithRepo.Branches.WithBranch.Protection {
    public var restrictions: Restrictions {
        Restrictions(path: path + "/restrictions")
    }

    public struct Restrictions {
        /// Path: `/repos/{owner}/{repo}/branches/{branch}/protection/restrictions`
        public let path: String

        /// Get access restrictions
        ///
        /// Protected branches are available in public repositories with GitHub Free and GitHub Free for organizations, and in public and private repositories with GitHub Pro, GitHub Team, GitHub Enterprise Cloud, and GitHub Enterprise Server. For more information, see [GitHub's products](https://help.github.com/github/getting-started-with-github/githubs-products) in the GitHub Help documentation.
        /// 
        /// Lists who has access to this protected branch.
        /// 
        /// **Note**: Users, apps, and teams `restrictions` are only available for organization-owned repositories.
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/repos#get-access-restrictions)
        public var get: Request<OctoKit.BranchRestrictionPolicy, GetError> {
            Request(path: path, method: "GET", id: "repos/get-access-restrictions")
        }

        public enum GetError: RequestError {
            case notFound(OctoKit.BasicError)
            case unhandled(any Swift.Error)

            public static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
                switch statusCode {
                case 404: return .notFound(try decoder.decode(OctoKit.BasicError.self, from: data))
                default: return .unhandled(APIError.unacceptableStatusCode(statusCode))
                }
            }
        }

        /// Delete access restrictions
        ///
        /// Protected branches are available in public repositories with GitHub Free and GitHub Free for organizations, and in public and private repositories with GitHub Pro, GitHub Team, GitHub Enterprise Cloud, and GitHub Enterprise Server. For more information, see [GitHub's products](https://help.github.com/github/getting-started-with-github/githubs-products) in the GitHub Help documentation.
        /// 
        /// Disables the ability to restrict who can push to this branch.
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/repos#delete-access-restrictions)
        public var delete: Request<Void, DefaultRequestError> {
            Request(path: path, method: "DELETE", id: "repos/delete-access-restrictions")
        }
    }
}
