// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
import HTTPHeaders
import TypedAPI
import URLQueryEncoder

extension Paths.Gists.WithGistID {
    public func sha(_ sha: String) -> WithSha {
        WithSha(path: "\(path)/\(sha)")
    }

    public struct WithSha {
        /// Path: `/gists/{gist_id}/{sha}`
        public let path: String

        /// Get a gist revision
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/gists#get-a-gist-revision)
        public var get: Request<OctoKit.GistSimple, GetError> {
            Request(path: path, method: "GET", id: "gists/get-revision")
        }

        public enum GetError: RequestError {
            case unprocessableEntity(OctoKit.ValidationError)
            case notFound(OctoKit.BasicError)
            case forbidden(OctoKit.BasicError)
            case unhandled(any Swift.Error)

            public static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
                switch statusCode {
                case 422: return .unprocessableEntity(try decoder.decode(OctoKit.ValidationError.self, from: data))
                case 404: return .notFound(try decoder.decode(OctoKit.BasicError.self, from: data))
                case 403: return .forbidden(try decoder.decode(OctoKit.BasicError.self, from: data))
                default: return .unhandled(APIError.unacceptableStatusCode(statusCode))
                }
            }
        }
    }
}
