// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import HTTPHeaders
import TypedAPI
import URLQueryEncoder

extension Paths.Networks.WithOwner.WithRepo {
    public var events: Events {
        Events(path: path + "/events")
    }

    public struct Events {
        /// Path: `/networks/{owner}/{repo}/events`
        public let path: String

        /// List public events for a network of repositories
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/activity#list-public-events-for-a-network-of-repositories)
        public func get(perPage: Int? = nil, page: Int? = nil) -> Request<[OctoKit.Event], GetError> {
            Request(path: path, method: "GET", query: makeGetQuery(perPage, page), id: "activity/list-public-events-for-repo-network")
        }

        public enum GetError: RequestError {
            case notFound(OctoKit.BasicError)
            case forbidden(OctoKit.BasicError)
            case notModified
            case movedPermanently(OctoKit.BasicError)
            case unhandled(any Swift.Error)

            public static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
                switch statusCode {
                case 404: return .notFound(try decoder.decode(OctoKit.BasicError.self, from: data))
                case 403: return .forbidden(try decoder.decode(OctoKit.BasicError.self, from: data))
                case 304: return .notModified
                case 301: return .movedPermanently(try decoder.decode(OctoKit.BasicError.self, from: data))
                default: return .unhandled(APIError.unacceptableStatusCode(statusCode))
                }
            }
        }

        private func makeGetQuery(_ perPage: Int?, _ page: Int?) -> [(String, String?)] {
            let encoder = URLQueryEncoder()
            encoder.encode(perPage, forKey: "per_page")
            encoder.encode(page, forKey: "page")
            return encoder.items
        }
    }
}
