// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
@preconcurrency import HTTPHeaders
import TypedAPI
import URLQueryEncoder

extension Paths.Projects.WithProjectID.Collaborators {
    public func username(_ username: String) -> WithUsername {
        WithUsername(path: "\(path)/\(username)")
    }

    public struct WithUsername {
        /// Path: `/projects/{project_id}/collaborators/{username}`
        public let path: String

        /// Add project collaborator
        ///
        /// Adds a collaborator to an organization project and sets their permission level. You must be an organization owner or a project `admin` to add a collaborator.
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/projects#add-project-collaborator)
        public func put(permission: PutRequest.Permission? = nil) -> Request<Void, PutError> {
            Request(path: path, method: "PUT", body: PutRequest(permission: permission), id: "projects/add-collaborator")
        }

        public enum PutError: RequestError {
            case notFound(OctoKit.BasicError)
            case unprocessableEntity(OctoKit.ValidationError)
            case notModified
            case forbidden(OctoKit.BasicError)
            case unauthorized(OctoKit.BasicError)
            case unhandled(any Swift.Error)

            public static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
                switch statusCode {
                case 404: return .notFound(try decoder.decode(OctoKit.BasicError.self, from: data))
                case 422: return .unprocessableEntity(try decoder.decode(OctoKit.ValidationError.self, from: data))
                case 304: return .notModified
                case 403: return .forbidden(try decoder.decode(OctoKit.BasicError.self, from: data))
                case 401: return .unauthorized(try decoder.decode(OctoKit.BasicError.self, from: data))
                default: return .unhandled(APIError.unacceptableStatusCode(statusCode))
                }
            }

            public var statusCode: Int? {
                switch self {
                case .notFound: return 404
                case .unprocessableEntity: return 422
                case .notModified: return 304
                case .forbidden: return 403
                case .unauthorized: return 401
                case .unhandled(let error): return (error as? APIError)?.statusCode
                }
            }

            public var underlyingError: (any Swift.Error)? {
                switch self {
                case .unhandled(let error): return error
                default: return nil
                }
            }
        }

        public struct PutRequest: Encodable, Sendable {
            /// The permission to grant the collaborator.
            ///
            /// Example: "write"
            public var permission: Permission?

            /// The permission to grant the collaborator.
            ///
            /// Example: "write"
            public enum Permission: String, Codable, CaseIterable, Sendable {
                case read
                case write
                case admin
            }

            public init(permission: Permission? = nil) {
                self.permission = permission
            }

            public func encode(to encoder: Encoder) throws {
                var values = encoder.container(keyedBy: StringCodingKey.self)
                try values.encodeIfPresent(permission, forKey: "permission")
            }
        }

        /// Remove user as a collaborator
        ///
        /// Removes a collaborator from an organization project. You must be an organization owner or a project `admin` to remove a collaborator.
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/projects#remove-project-collaborator)
        public var delete: Request<Void, DeleteError> {
            Request(path: path, method: "DELETE", id: "projects/remove-collaborator")
        }

        public enum DeleteError: RequestError {
            case notModified
            case notFound(OctoKit.BasicError)
            case forbidden(OctoKit.BasicError)
            case unprocessableEntity(OctoKit.ValidationError)
            case unauthorized(OctoKit.BasicError)
            case unhandled(any Swift.Error)

            public static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
                switch statusCode {
                case 304: return .notModified
                case 404: return .notFound(try decoder.decode(OctoKit.BasicError.self, from: data))
                case 403: return .forbidden(try decoder.decode(OctoKit.BasicError.self, from: data))
                case 422: return .unprocessableEntity(try decoder.decode(OctoKit.ValidationError.self, from: data))
                case 401: return .unauthorized(try decoder.decode(OctoKit.BasicError.self, from: data))
                default: return .unhandled(APIError.unacceptableStatusCode(statusCode))
                }
            }

            public var statusCode: Int? {
                switch self {
                case .notModified: return 304
                case .notFound: return 404
                case .forbidden: return 403
                case .unprocessableEntity: return 422
                case .unauthorized: return 401
                case .unhandled(let error): return (error as? APIError)?.statusCode
                }
            }

            public var underlyingError: (any Swift.Error)? {
                switch self {
                case .unhandled(let error): return error
                default: return nil
                }
            }
        }
    }
}
