// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import HTTPHeaders
import TypedAPI
import URLQueryEncoder

extension Paths.App.Installations {
    public func installationID(_ installationID: Int) -> WithInstallationID {
        WithInstallationID(path: "\(path)/\(installationID)")
    }

    public struct WithInstallationID {
        /// Path: `/app/installations/{installation_id}`
        public let path: String

        /// Get an installation for the authenticated app
        ///
        /// Enables an authenticated GitHub App to find an installation's information using the installation id. The installation's account type (`target_type`) will be either an organization or a user account, depending which account the repository belongs to.
        /// 
        /// You must use a [JWT](https://docs.github.com/apps/building-github-apps/authenticating-with-github-apps/#authenticating-as-a-github-app) to access this endpoint.
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/apps#get-an-installation-for-the-authenticated-app)
        public var get: Request<OctoKit.Installation, GetError> {
            Request(path: path, method: "GET", id: "apps/get-installation")
        }

        public enum GetError: RequestError {
            case notFound(OctoKit.BasicError)
            case unsupportedMediaType(GetUnsupportedMediaTypeBody)
            case unhandled(any Swift.Error)

            public static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
                switch statusCode {
                case 404: return .notFound(try decoder.decode(OctoKit.BasicError.self, from: data))
                case 415: return .unsupportedMediaType(try decoder.decode(GetUnsupportedMediaTypeBody.self, from: data))
                default: return .unhandled(APIError.unacceptableStatusCode(statusCode))
                }
            }
        }

        public struct GetUnsupportedMediaTypeBody: Decodable, Sendable {
            public var message: String
            public var documentationURL: String

            public init(message: String, documentationURL: String) {
                self.message = message
                self.documentationURL = documentationURL
            }

            public init(from decoder: Decoder) throws {
                let values = try decoder.container(keyedBy: StringCodingKey.self)
                self.message = try values.decode(String.self, forKey: "message")
                self.documentationURL = try values.decode(String.self, forKey: "documentation_url")
            }
        }

        /// Delete an installation for the authenticated app
        ///
        /// Uninstalls a GitHub App on a user, organization, or business account. If you prefer to temporarily suspend an app's access to your account's resources, then we recommend the "[Suspend an app installation](https://docs.github.com/rest/reference/apps/#suspend-an-app-installation)" endpoint.
        /// 
        /// You must use a [JWT](https://docs.github.com/apps/building-github-apps/authenticating-with-github-apps/#authenticating-as-a-github-app) to access this endpoint.
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/apps#delete-an-installation-for-the-authenticated-app)
        public var delete: Request<Void, DeleteError> {
            Request(path: path, method: "DELETE", id: "apps/delete-installation")
        }

        public enum DeleteError: RequestError {
            case notFound(OctoKit.BasicError)
            case unhandled(any Swift.Error)

            public static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
                switch statusCode {
                case 404: return .notFound(try decoder.decode(OctoKit.BasicError.self, from: data))
                default: return .unhandled(APIError.unacceptableStatusCode(statusCode))
                }
            }
        }
    }
}
