// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import HTTPHeaders
import TypedAPI
import URLQueryEncoder

extension Paths.Projects.Columns.WithColumnID {
    public var cards: Cards {
        Cards(path: path + "/cards")
    }

    public struct Cards {
        /// Path: `/projects/columns/{column_id}/cards`
        public let path: String

        /// List project cards
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/projects#list-project-cards)
        public func get(parameters: GetParameters? = nil) -> Request<[OctoKit.ProjectCard], GetError> {
            Request(path: path, method: "GET", query: parameters?.asQuery, id: "projects/list-cards")
        }

        public enum GetError: RequestError {
            case notModified
            case forbidden(OctoKit.BasicError)
            case unauthorized(OctoKit.BasicError)
            case unhandled(any Swift.Error)

            public static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
                switch statusCode {
                case 304: return .notModified
                case 403: return .forbidden(try decoder.decode(OctoKit.BasicError.self, from: data))
                case 401: return .unauthorized(try decoder.decode(OctoKit.BasicError.self, from: data))
                default: return .unhandled(APIError.unacceptableStatusCode(statusCode))
                }
            }
        }

        public enum GetResponseHeaders {
            public static let link = HTTPHeader<String>(field: "Link")
        }

        public struct GetParameters {
            public var archivedState: ArchivedState?
            public var perPage: Int?
            public var page: Int?

            public enum ArchivedState: String, Codable, CaseIterable {
                case all
                case archived
                case notArchived = "not_archived"
            }

            public init(archivedState: ArchivedState? = nil, perPage: Int? = nil, page: Int? = nil) {
                self.archivedState = archivedState
                self.perPage = perPage
                self.page = page
            }

            public var asQuery: [(String, String?)] {
                let encoder = URLQueryEncoder()
                encoder.encode(archivedState, forKey: "archived_state")
                encoder.encode(perPage, forKey: "per_page")
                encoder.encode(page, forKey: "page")
                return encoder.items
            }
        }

        /// Create a project card
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/projects#create-a-project-card)
        public func post(_ body: PostRequest) -> Request<OctoKit.ProjectCard, PostError> {
            Request(path: path, method: "POST", body: body, id: "projects/create-card")
        }

        public enum PostError: RequestError {
            case notModified
            case forbidden(OctoKit.BasicError)
            case unauthorized(OctoKit.BasicError)
            case unprocessableEntity(PostUnprocessableEntityBody)
            case serviceUnavailable(PostServiceUnavailableBody)
            case unhandled(any Swift.Error)

            public static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
                switch statusCode {
                case 304: return .notModified
                case 403: return .forbidden(try decoder.decode(OctoKit.BasicError.self, from: data))
                case 401: return .unauthorized(try decoder.decode(OctoKit.BasicError.self, from: data))
                case 422: return .unprocessableEntity(try decoder.decode(PostUnprocessableEntityBody.self, from: data))
                case 503: return .serviceUnavailable(try decoder.decode(PostServiceUnavailableBody.self, from: data))
                default: return .unhandled(APIError.unacceptableStatusCode(statusCode))
                }
            }
        }

        public enum PostUnprocessableEntityBody: Decodable {
            case validationError(OctoKit.ValidationError)
            case validationErrorSimple(OctoKit.ValidationErrorSimple)

            public init(from decoder: Decoder) throws {
                let container = try decoder.singleValueContainer()
                if let value = try? container.decode(OctoKit.ValidationError.self) {
                    self = .validationError(value)
                } else if let value = try? container.decode(OctoKit.ValidationErrorSimple.self) {
                    self = .validationErrorSimple(value)
                } else {
                    throw DecodingError.dataCorruptedError(
                        in: container,
                        debugDescription: "Data could not be decoded as any of the expected types (OctoKit.ValidationError, OctoKit.ValidationErrorSimple)."
                    )
                }
            }
        }

        public struct PostServiceUnavailableBody: Decodable {
            public var code: String?
            public var message: String?
            public var documentationURL: String?
            public var errors: [Error]?

            public struct Error: Decodable {
                public var code: String?
                public var message: String?

                public init(code: String? = nil, message: String? = nil) {
                    self.code = code
                    self.message = message
                }

                public init(from decoder: Decoder) throws {
                    let values = try decoder.container(keyedBy: StringCodingKey.self)
                    self.code = try values.decodeIfPresent(String.self, forKey: "code")
                    self.message = try values.decodeIfPresent(String.self, forKey: "message")
                }
            }

            public init(code: String? = nil, message: String? = nil, documentationURL: String? = nil, errors: [Error]? = nil) {
                self.code = code
                self.message = message
                self.documentationURL = documentationURL
                self.errors = errors
            }

            public init(from decoder: Decoder) throws {
                let values = try decoder.container(keyedBy: StringCodingKey.self)
                self.code = try values.decodeIfPresent(String.self, forKey: "code")
                self.message = try values.decodeIfPresent(String.self, forKey: "message")
                self.documentationURL = try values.decodeIfPresent(String.self, forKey: "documentation_url")
                self.errors = try values.decodeIfPresent([Error].self, forKey: "errors")
            }
        }

        public enum PostRequest: Encodable {
            case a(A)
            case b(B)

            public struct A: Encodable {
                /// The project card's note
                ///
                /// Example: "Update all gems"
                public var note: String?

                public init(note: String? = nil) {
                    self.note = note
                }

                public func encode(to encoder: Encoder) throws {
                    var values = encoder.container(keyedBy: StringCodingKey.self)
                    try values.encodeIfPresent(note, forKey: "note")
                }
            }

            public struct B: Encodable {
                /// The unique identifier of the content associated with the card
                ///
                /// Example: 42
                public var contentID: Int
                /// The piece of content associated with the card
                ///
                /// Example: "PullRequest"
                public var contentType: String

                public init(contentID: Int, contentType: String) {
                    self.contentID = contentID
                    self.contentType = contentType
                }

                public func encode(to encoder: Encoder) throws {
                    var values = encoder.container(keyedBy: StringCodingKey.self)
                    try values.encode(contentID, forKey: "content_id")
                    try values.encode(contentType, forKey: "content_type")
                }
            }

            public func encode(to encoder: Encoder) throws {
                var container = encoder.singleValueContainer()
                switch self {
                case .a(let value): try container.encode(value)
                case .b(let value): try container.encode(value)
                }
            }
        }
    }
}
