// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import HTTPHeaders
import URLQueryEncoder

extension Paths.Repos.WithOwner.WithRepo.Comments {
    public func commentID(_ commentID: Int) -> WithCommentID {
        WithCommentID(path: "\(path)/\(commentID)")
    }

    public struct WithCommentID {
        /// Path: `/repos/{owner}/{repo}/comments/{comment_id}`
        public let path: String

        /// Get a commit comment
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/repos#get-a-commit-comment)
        public var get: Request<OctoKit.CommitComment> {
            get throws(GetError) {
                Request(path: path, method: "GET", id: "repos/get-commit-comment")
            }
        }

        public enum GetError: Error {
            case notFound(OctoKit.BasicError)
        }

        /// Update a commit comment
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/repos#update-a-commit-comment)
        public func patch(body: String) throws(PatchError) -> Request<OctoKit.CommitComment> {
            Request(path: path, method: "PATCH", body: ["body": body], id: "repos/update-commit-comment")
        }

        public enum PatchError: Error {
            case notFound(OctoKit.BasicError)
        }

        /// Delete a commit comment
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/repos#delete-a-commit-comment)
        public var delete: Request<Void> {
            get throws(DeleteError) {
                Request(path: path, method: "DELETE", id: "repos/delete-commit-comment")
            }
        }

        public enum DeleteError: Error {
            case notFound(OctoKit.BasicError)
        }
    }
}
