// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import HTTPHeaders
import TypedAPI
import URLQueryEncoder

extension Paths.User.Migrations.WithMigrationID.Repos.WithRepoName {
    public var lock: Lock {
        Lock(path: path + "/lock")
    }

    public struct Lock {
        /// Path: `/user/migrations/{migration_id}/repos/{repo_name}/lock`
        public let path: String

        /// Unlock a user repository
        ///
        /// Unlocks a repository. You can lock repositories when you [start a user migration](https://docs.github.com/rest/reference/migrations#start-a-user-migration). Once the migration is complete you can unlock each repository to begin using it again or [delete the repository](https://docs.github.com/rest/reference/repos#delete-a-repository) if you no longer need the source data. Returns a status of `404 Not Found` if the repository is not locked.
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/migrations#unlock-a-user-repository)
        public var delete: Request<Void, DeleteError> {
            Request(path: path, method: "DELETE", id: "migrations/unlock-repo-for-authenticated-user")
        }

        public enum DeleteError: RequestError {
            case notModified
            case notFound(OctoKit.BasicError)
            case forbidden(OctoKit.BasicError)
            case unauthorized(OctoKit.BasicError)
            case unhandled(any Swift.Error)

            public static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
                switch statusCode {
                case 304: return .notModified
                case 404: return .notFound(try decoder.decode(OctoKit.BasicError.self, from: data))
                case 403: return .forbidden(try decoder.decode(OctoKit.BasicError.self, from: data))
                case 401: return .unauthorized(try decoder.decode(OctoKit.BasicError.self, from: data))
                default: return .unhandled(APIError.unacceptableStatusCode(statusCode))
                }
            }
        }
    }
}
