// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
import HTTPHeaders
import TypedAPI
import URLQueryEncoder

extension Paths.Users.WithUsername.Packages {
    public func packageType(_ packageType: String) -> WithPackageType {
        WithPackageType(path: "\(path)/\(packageType)")
    }

    public struct WithPackageType {
        /// Path: `/users/{username}/packages/{package_type}`
        public let path: String
    }
}
