// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import HTTPHeaders
import TypedAPI
import URLQueryEncoder

extension Paths.Repos.WithOwner.WithRepo.Pulls.WithPullNumber {
    public var files: Files {
        Files(path: path + "/files")
    }

    public struct Files {
        /// Path: `/repos/{owner}/{repo}/pulls/{pull_number}/files`
        public let path: String

        /// List pull requests files
        ///
        /// **Note:** Responses include a maximum of 3000 files. The paginated response returns 30 files per page by default.
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/pulls#list-pull-requests-files)
        public func get(perPage: Int? = nil, page: Int? = nil) -> Request<[OctoKit.DiffEntry], GetError> {
            Request(path: path, method: "GET", query: makeGetQuery(perPage, page), id: "pulls/list-files")
        }

        public enum GetError: RequestError {
            case unprocessableEntity(OctoKit.ValidationError)
            case internalServerError(OctoKit.BasicError)
            case unhandled(any Swift.Error)

            public static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
                switch statusCode {
                case 422: return .unprocessableEntity(try decoder.decode(OctoKit.ValidationError.self, from: data))
                case 500: return .internalServerError(try decoder.decode(OctoKit.BasicError.self, from: data))
                default: return .unhandled(APIError.unacceptableStatusCode(statusCode))
                }
            }
        }

        public enum GetResponseHeaders {
            public static let link = HTTPHeader<String>(field: "Link")
        }

        private func makeGetQuery(_ perPage: Int?, _ page: Int?) -> [(String, String?)] {
            let encoder = URLQueryEncoder()
            encoder.encode(perPage, forKey: "per_page")
            encoder.encode(page, forKey: "page")
            return encoder.items
        }
    }
}
