// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
import HTTPHeaders
import TypedAPI
import URLQueryEncoder

extension Paths.Gists {
    public var starred: Starred {
        Starred(path: path + "/starred")
    }

    public struct Starred {
        /// Path: `/gists/starred`
        public let path: String

        /// List starred gists
        ///
        /// List the authenticated user's starred gists:
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/gists#list-starred-gists)
        public func get(parameters: GetParameters? = nil) -> Request<[OctoKit.BaseGist], GetError> {
            Request(path: path, method: "GET", query: parameters?.asQuery, id: "gists/list-starred")
        }

        public enum GetError: RequestError {
            case unauthorized(OctoKit.BasicError)
            case notModified
            case forbidden(OctoKit.BasicError)
            case unhandled(any Swift.Error)

            public static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
                switch statusCode {
                case 401: return .unauthorized(try decoder.decode(OctoKit.BasicError.self, from: data))
                case 304: return .notModified
                case 403: return .forbidden(try decoder.decode(OctoKit.BasicError.self, from: data))
                default: return .unhandled(APIError.unacceptableStatusCode(statusCode))
                }
            }
        }

        public enum GetResponseHeaders {
            public static let link = HTTPHeader<String>(field: "Link")
        }

        public struct GetParameters {
            public var since: Date?
            public var perPage: Int?
            public var page: Int?

            public init(since: Date? = nil, perPage: Int? = nil, page: Int? = nil) {
                self.since = since
                self.perPage = perPage
                self.page = page
            }

            public var asQuery: [(String, String?)] {
                let encoder = URLQueryEncoder()
                encoder.encode(since, forKey: "since")
                encoder.encode(perPage, forKey: "per_page")
                encoder.encode(page, forKey: "page")
                return encoder.items
            }
        }
    }
}
