// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
import HTTPHeaders
import TypedAPI
import URLQueryEncoder

extension Paths.Repos.WithOwner.WithRepo.Issues.WithIssueNumber {
    public var comments: Comments {
        Comments(path: path + "/comments")
    }

    public struct Comments {
        /// Path: `/repos/{owner}/{repo}/issues/{issue_number}/comments`
        public let path: String

        /// List issue comments
        ///
        /// Issue Comments are ordered by ascending ID.
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/issues#list-issue-comments)
        public func get(parameters: GetParameters? = nil) -> Request<[OctoKit.IssueComment], GetError> {
            Request(path: path, method: "GET", query: parameters?.asQuery, id: "issues/list-comments")
        }

        public enum GetError: RequestError {
            case notFound(OctoKit.BasicError)
            case gone(OctoKit.BasicError)
            case unhandled(any Swift.Error)

            public static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
                switch statusCode {
                case 404: return .notFound(try decoder.decode(OctoKit.BasicError.self, from: data))
                case 410: return .gone(try decoder.decode(OctoKit.BasicError.self, from: data))
                default: return .unhandled(APIError.unacceptableStatusCode(statusCode))
                }
            }
        }

        public enum GetResponseHeaders {
            public static let link = HTTPHeader<String>(field: "Link")
        }

        public struct GetParameters {
            public var since: Date?
            public var perPage: Int?
            public var page: Int?

            public init(since: Date? = nil, perPage: Int? = nil, page: Int? = nil) {
                self.since = since
                self.perPage = perPage
                self.page = page
            }

            public var asQuery: [(String, String?)] {
                let encoder = URLQueryEncoder()
                encoder.encode(since, forKey: "since")
                encoder.encode(perPage, forKey: "per_page")
                encoder.encode(page, forKey: "page")
                return encoder.items
            }
        }

        /// Create an issue comment
        ///
        /// This endpoint triggers [notifications](https://docs.github.com/en/github/managing-subscriptions-and-notifications-on-github/about-notifications). Creating content too quickly using this endpoint may result in secondary rate limiting. See "[Secondary rate limits](https://docs.github.com/rest/overview/resources-in-the-rest-api#secondary-rate-limits)" and "[Dealing with secondary rate limits](https://docs.github.com/rest/guides/best-practices-for-integrators#dealing-with-secondary-rate-limits)" for details.
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/issues#create-an-issue-comment)
        public func post(body: String) -> Request<OctoKit.IssueComment, PostError> {
            Request(path: path, method: "POST", body: ["body": body], id: "issues/create-comment")
        }

        public enum PostError: RequestError {
            case forbidden(OctoKit.BasicError)
            case gone(OctoKit.BasicError)
            case unprocessableEntity(OctoKit.ValidationError)
            case notFound(OctoKit.BasicError)
            case unhandled(any Swift.Error)

            public static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
                switch statusCode {
                case 403: return .forbidden(try decoder.decode(OctoKit.BasicError.self, from: data))
                case 410: return .gone(try decoder.decode(OctoKit.BasicError.self, from: data))
                case 422: return .unprocessableEntity(try decoder.decode(OctoKit.ValidationError.self, from: data))
                case 404: return .notFound(try decoder.decode(OctoKit.BasicError.self, from: data))
                default: return .unhandled(APIError.unacceptableStatusCode(statusCode))
                }
            }
        }

        public enum PostResponseHeaders {
            public static let location = HTTPHeader<String>(field: "Location")
        }
    }
}
