// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import HTTPHeaders
import TypedAPI
import URLQueryEncoder

extension Paths.Repos.WithOwner.WithRepo.Branches.WithBranch {
    public var rename: Rename {
        Rename(path: path + "/rename")
    }

    public struct Rename {
        /// Path: `/repos/{owner}/{repo}/branches/{branch}/rename`
        public let path: String

        /// Rename a branch
        ///
        /// Renames a branch in a repository.
        /// 
        /// **Note:** Although the API responds immediately, the branch rename process might take some extra time to complete in the background. You won't be able to push to the old branch name while the rename process is in progress. For more information, see "[Renaming a branch](https://docs.github.com/github/administering-a-repository/renaming-a-branch)".
        /// 
        /// The permissions required to use this endpoint depends on whether you are renaming the default branch.
        /// 
        /// To rename a non-default branch:
        /// 
        /// * Users must have push access.
        /// * GitHub Apps must have the `contents:write` repository permission.
        /// 
        /// To rename the default branch:
        /// 
        /// * Users must have admin or owner permissions.
        /// * GitHub Apps must have the `administration:write` repository permission.
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/repos#rename-a-branch)
        public func post(newName: String) -> Request<OctoKit.BranchWithProtection, PostError> {
            Request(path: path, method: "POST", body: ["new_name": newName], id: "repos/rename-branch")
        }

        public enum PostError: RequestError {
            case forbidden(OctoKit.BasicError)
            case notFound(OctoKit.BasicError)
            case unprocessableEntity(OctoKit.ValidationError)
            case unhandled(any Swift.Error)

            public static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
                switch statusCode {
                case 403: return .forbidden(try decoder.decode(OctoKit.BasicError.self, from: data))
                case 404: return .notFound(try decoder.decode(OctoKit.BasicError.self, from: data))
                case 422: return .unprocessableEntity(try decoder.decode(OctoKit.ValidationError.self, from: data))
                default: return .unhandled(APIError.unacceptableStatusCode(statusCode))
                }
            }
        }
    }
}
