// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import HTTPHeaders
import TypedAPI
import URLQueryEncoder

extension Paths.Gists.WithGistID {
    public var comments: Comments {
        Comments(path: path + "/comments")
    }

    public struct Comments {
        /// Path: `/gists/{gist_id}/comments`
        public let path: String

        /// List gist comments
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/gists#list-gist-comments)
        public func get(perPage: Int? = nil, page: Int? = nil) -> Request<[OctoKit.GistComment], GetError> {
            Request(path: path, method: "GET", query: makeGetQuery(perPage, page), id: "gists/list-comments")
        }

        public enum GetError: RequestError {
            case notModified
            case notFound(OctoKit.BasicError)
            case forbidden(OctoKit.BasicError)
            case unhandled(any Swift.Error)

            public static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
                switch statusCode {
                case 304: return .notModified
                case 404: return .notFound(try decoder.decode(OctoKit.BasicError.self, from: data))
                case 403: return .forbidden(try decoder.decode(OctoKit.BasicError.self, from: data))
                default: return .unhandled(APIError.unacceptableStatusCode(statusCode))
                }
            }
        }

        public enum GetResponseHeaders {
            public static let link = HTTPHeader<String>(field: "Link")
        }

        private func makeGetQuery(_ perPage: Int?, _ page: Int?) -> [(String, String?)] {
            let encoder = URLQueryEncoder()
            encoder.encode(perPage, forKey: "per_page")
            encoder.encode(page, forKey: "page")
            return encoder.items
        }

        /// Create a gist comment
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/gists#create-a-gist-comment)
        public func post(body: String) -> Request<OctoKit.GistComment, PostError> {
            Request(path: path, method: "POST", body: ["body": body], id: "gists/create-comment")
        }

        public enum PostError: RequestError {
            case notModified
            case notFound(OctoKit.BasicError)
            case forbidden(OctoKit.BasicError)
            case unhandled(any Swift.Error)

            public static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
                switch statusCode {
                case 304: return .notModified
                case 404: return .notFound(try decoder.decode(OctoKit.BasicError.self, from: data))
                case 403: return .forbidden(try decoder.decode(OctoKit.BasicError.self, from: data))
                default: return .unhandled(APIError.unacceptableStatusCode(statusCode))
                }
            }
        }

        public enum PostResponseHeaders {
            public static let location = HTTPHeader<String>(field: "Location")
        }
    }
}
