// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import HTTPHeaders
import TypedAPI
import URLQueryEncoder

extension Paths.User.Migrations.WithMigrationID.Repos {
    public func repoName(_ repoName: String) -> WithRepoName {
        WithRepoName(path: "\(path)/\(repoName)")
    }

    public struct WithRepoName {
        /// Path: `/user/migrations/{migration_id}/repos/{repo_name}`
        public let path: String
    }
}
