// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
import HTTPHeaders
import TypedAPI
import URLQueryEncoder

extension Paths.Orgs.WithOrg.Migrations.WithMigrationID.Repos {
    public func repoName(_ repoName: String) -> WithRepoName {
        WithRepoName(path: "\(path)/\(repoName)")
    }

    public struct WithRepoName {
        /// Path: `/orgs/{org}/migrations/{migration_id}/repos/{repo_name}`
        public let path: String
    }
}
