// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
import HTTPHeaders
import TypedAPI
import URLQueryEncoder

extension Paths.Repos.WithOwner.WithRepo.Branches.WithBranch.Protection {
    public var enforceAdmins: EnforceAdmins {
        EnforceAdmins(path: path + "/enforce_admins")
    }

    public struct EnforceAdmins {
        /// Path: `/repos/{owner}/{repo}/branches/{branch}/protection/enforce_admins`
        public let path: String

        /// Get admin branch protection
        ///
        /// Protected branches are available in public repositories with GitHub Free and GitHub Free for organizations, and in public and private repositories with GitHub Pro, GitHub Team, GitHub Enterprise Cloud, and GitHub Enterprise Server. For more information, see [GitHub's products](https://help.github.com/github/getting-started-with-github/githubs-products) in the GitHub Help documentation.
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/repos#get-admin-branch-protection)
        public var get: Request<OctoKit.ProtectedBranchAdminEnforced, DefaultRequestError> {
            Request(path: path, method: "GET", id: "repos/get-admin-branch-protection")
        }

        /// Set admin branch protection
        ///
        /// Protected branches are available in public repositories with GitHub Free and GitHub Free for organizations, and in public and private repositories with GitHub Pro, GitHub Team, GitHub Enterprise Cloud, and GitHub Enterprise Server. For more information, see [GitHub's products](https://help.github.com/github/getting-started-with-github/githubs-products) in the GitHub Help documentation.
        /// 
        /// Adding admin enforcement requires admin or owner permissions to the repository and branch protection to be enabled.
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/repos#set-admin-branch-protection)
        public var post: Request<OctoKit.ProtectedBranchAdminEnforced, DefaultRequestError> {
            Request(path: path, method: "POST", id: "repos/set-admin-branch-protection")
        }

        /// Delete admin branch protection
        ///
        /// Protected branches are available in public repositories with GitHub Free and GitHub Free for organizations, and in public and private repositories with GitHub Pro, GitHub Team, GitHub Enterprise Cloud, and GitHub Enterprise Server. For more information, see [GitHub's products](https://help.github.com/github/getting-started-with-github/githubs-products) in the GitHub Help documentation.
        /// 
        /// Removing admin enforcement requires admin or owner permissions to the repository and branch protection to be enabled.
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/repos#delete-admin-branch-protection)
        public var delete: Request<Void, DeleteError> {
            Request(path: path, method: "DELETE", id: "repos/delete-admin-branch-protection")
        }

        public enum DeleteError: RequestError {
            case notFound(OctoKit.BasicError)
            case unhandled(any Swift.Error)

            public static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
                switch statusCode {
                case 404: return .notFound(try decoder.decode(OctoKit.BasicError.self, from: data))
                default: return .unhandled(APIError.unacceptableStatusCode(statusCode))
                }
            }
        }
    }
}
