// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import HTTPHeaders
import URLQueryEncoder

extension Paths {
    public static var events: Events {
        Events(path: "/events")
    }

    public struct Events {
        /// Path: `/events`
        public let path: String

        /// List public events
        ///
        /// We delay the public events feed by five minutes, which means the most recent event returned by the public events API actually occurred at least five minutes ago.
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/activity#list-public-events)
        public func get(perPage: Int? = nil, page: Int? = nil) throws(GetError) -> Request<[OctoKit.Event]> {
            Request(path: path, method: "GET", query: makeGetQuery(perPage, page), id: "activity/list-public-events")
        }

        public enum GetError: Error {
            case notModified
            case forbidden(OctoKit.BasicError)
            case serviceUnavailable(GetServiceUnavailableBody)
        }

        public struct GetServiceUnavailableBody: Decodable {
            public var code: String?
            public var message: String?
            public var documentationURL: String?

            public init(code: String? = nil, message: String? = nil, documentationURL: String? = nil) {
                self.code = code
                self.message = message
                self.documentationURL = documentationURL
            }

            public init(from decoder: Decoder) throws {
                let values = try decoder.container(keyedBy: StringCodingKey.self)
                self.code = try values.decodeIfPresent(String.self, forKey: "code")
                self.message = try values.decodeIfPresent(String.self, forKey: "message")
                self.documentationURL = try values.decodeIfPresent(String.self, forKey: "documentation_url")
            }
        }

        private func makeGetQuery(_ perPage: Int?, _ page: Int?) -> [(String, String?)] {
            let encoder = URLQueryEncoder()
            encoder.encode(perPage, forKey: "per_page")
            encoder.encode(page, forKey: "page")
            return encoder.items
        }
    }
}
