// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import HTTPHeaders
import TypedAPI
import URLQueryEncoder

extension Paths {
    public static var enterprises: Enterprises {
        Enterprises(path: "/enterprises")
    }

    public struct Enterprises {
        /// Path: `/enterprises`
        public let path: String
    }
}
