// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import HTTPHeaders
import TypedAPI
import URLQueryEncoder

extension Paths.Repos.WithOwner.WithRepo {
    public var readme: Readme {
        Readme(path: path + "/readme")
    }

    public struct Readme {
        /// Path: `/repos/{owner}/{repo}/readme`
        public let path: String

        /// Get a repository README
        ///
        /// Gets the preferred README for a repository.
        /// 
        /// READMEs support [custom media types](https://docs.github.com/rest/reference/repos#custom-media-types) for retrieving the raw content or rendered HTML.
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/repos#get-a-repository-readme)
        public func get(ref: String? = nil) -> Request<OctoKit.ContentFile, GetError> {
            Request(path: path, method: "GET", query: makeGetQuery(ref), id: "repos/get-readme")
        }

        public enum GetError: RequestError {
            case notFound(OctoKit.BasicError)
            case unprocessableEntity(OctoKit.ValidationError)
            case unhandled(any Swift.Error)

            public static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
                switch statusCode {
                case 404: return .notFound(try decoder.decode(OctoKit.BasicError.self, from: data))
                case 422: return .unprocessableEntity(try decoder.decode(OctoKit.ValidationError.self, from: data))
                default: return .unhandled(APIError.unacceptableStatusCode(statusCode))
                }
            }
        }

        private func makeGetQuery(_ ref: String?) -> [(String, String?)] {
            let encoder = URLQueryEncoder()
            encoder.encode(ref, forKey: "ref")
            return encoder.items
        }
    }
}
