// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
import HTTPHeaders
import TypedAPI
import URLQueryEncoder

extension Paths.Repos.WithOwner.WithRepo.CodeScanning.Alerts.WithAlertNumber {
    public var instances: Instances {
        Instances(path: path + "/instances")
    }

    public struct Instances {
        /// Path: `/repos/{owner}/{repo}/code-scanning/alerts/{alert_number}/instances`
        public let path: String

        /// List instances of a code scanning alert
        ///
        /// Lists all instances of the specified code scanning alert.
        /// You must use an access token with the `security_events` scope to use this endpoint with private repos,
        /// the `public_repo` scope also grants permission to read security events on public repos only.
        /// GitHub Apps must have the `security_events` read permission to use this endpoint.
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/code-scanning#list-instances-of-a-code-scanning-alert)
        public func get(parameters: GetParameters? = nil) -> Request<[OctoKit.CodeScanningAlertInstance], GetError> {
            Request(path: path, method: "GET", query: parameters?.asQuery, id: "code-scanning/list-alert-instances")
        }

        public enum GetError: RequestError {
            case forbidden(OctoKit.BasicError)
            case notFound(OctoKit.BasicError)
            case serviceUnavailable(GetServiceUnavailableBody)
            case unhandled(any Swift.Error)

            public static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
                switch statusCode {
                case 403: return .forbidden(try decoder.decode(OctoKit.BasicError.self, from: data))
                case 404: return .notFound(try decoder.decode(OctoKit.BasicError.self, from: data))
                case 503: return .serviceUnavailable(try decoder.decode(GetServiceUnavailableBody.self, from: data))
                default: return .unhandled(APIError.unacceptableStatusCode(statusCode))
                }
            }
        }

        public struct GetServiceUnavailableBody: Decodable, Sendable {
            public var code: String?
            public var message: String?
            public var documentationURL: String?

            public init(code: String? = nil, message: String? = nil, documentationURL: String? = nil) {
                self.code = code
                self.message = message
                self.documentationURL = documentationURL
            }

            public init(from decoder: Decoder) throws {
                let values = try decoder.container(keyedBy: StringCodingKey.self)
                self.code = try values.decodeIfPresent(String.self, forKey: "code")
                self.message = try values.decodeIfPresent(String.self, forKey: "message")
                self.documentationURL = try values.decodeIfPresent(String.self, forKey: "documentation_url")
            }
        }

        public struct GetParameters {
            public var page: Int?
            public var perPage: Int?
            /// The full Git reference, formatted as `refs/heads/<branch name>`,
            /// `refs/pull/<number>/merge`, or `refs/pull/<number>/head`.
            public var ref: String?

            public init(page: Int? = nil, perPage: Int? = nil, ref: String? = nil) {
                self.page = page
                self.perPage = perPage
                self.ref = ref
            }

            public var asQuery: [(String, String?)] {
                let encoder = URLQueryEncoder()
                encoder.encode(page, forKey: "page")
                encoder.encode(perPage, forKey: "per_page")
                encoder.encode(ref, forKey: "ref")
                return encoder.items
            }
        }
    }
}
