// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import HTTPHeaders
import TypedAPI
import URLQueryEncoder

extension Paths {
    public static var appManifests: AppManifests {
        AppManifests(path: "/app-manifests")
    }

    public struct AppManifests {
        /// Path: `/app-manifests`
        public let path: String
    }
}
