// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
import HTTPHeaders
import TypedAPI
import URLQueryEncoder

extension Paths.AppManifests {
    public func code(_ code: String) -> WithCode {
        WithCode(path: "\(path)/\(code)")
    }

    public struct WithCode {
        /// Path: `/app-manifests/{code}`
        public let path: String
    }
}
