// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
@preconcurrency import HTTPHeaders
import TypedAPI
import URLQueryEncoder

extension Paths.Repos.WithOwner.WithRepo.Pulls.WithPullNumber {
    public var updateBranch: UpdateBranch {
        UpdateBranch(path: path + "/update-branch")
    }

    public struct UpdateBranch {
        /// Path: `/repos/{owner}/{repo}/pulls/{pull_number}/update-branch`
        public let path: String

        /// Update a pull request branch
        ///
        /// Updates the pull request branch with the latest upstream changes by merging HEAD from the base branch into the pull request branch.
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/pulls#update-a-pull-request-branch)
        public func put(expectedHeadSha: String? = nil) -> Request<Void, PutError> {
            Request(path: path, method: "PUT", body: ["expected_head_sha": expectedHeadSha], id: "pulls/update-branch")
        }

        public enum PutError: RequestError {
            case unprocessableEntity(OctoKit.ValidationError)
            case forbidden(OctoKit.BasicError)
            case unhandled(any Swift.Error)

            public static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
                switch statusCode {
                case 422: return .unprocessableEntity(try decoder.decode(OctoKit.ValidationError.self, from: data))
                case 403: return .forbidden(try decoder.decode(OctoKit.BasicError.self, from: data))
                default: return .unhandled(APIError.unacceptableStatusCode(statusCode))
                }
            }

            public var statusCode: Int? {
                switch self {
                case .unprocessableEntity: return 422
                case .forbidden: return 403
                case .unhandled(let error): return (error as? APIError)?.statusCode
                }
            }

            public var underlyingError: (any Swift.Error)? {
                switch self {
                case .unhandled(let error): return error
                default: return nil
                }
            }
        }
    }
}
