// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import HTTPHeaders
import URLQueryEncoder

extension Paths.User.Codespaces.WithCodespaceName {
    public var start: Start {
        Start(path: path + "/start")
    }

    public struct Start {
        /// Path: `/user/codespaces/{codespace_name}/start`
        public let path: String

        /// Start a codespace for the authenticated user
        ///
        /// Starts a user's codespace.
        /// 
        /// You must authenticate using an access token with the `codespace` scope to use this endpoint.
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/codespaces#start-a-codespace-for-the-authenticated-user)
        public var post: Request<OctoKit.Codespace> {
            get throws(PostError) {
                Request(path: path, method: "POST", id: "codespaces/start-for-authenticated-user")
            }
        }

        public enum PostError: Error {
            case notModified
            case internalServerError(OctoKit.BasicError)
            case badRequest(OctoKit.BasicError)
            case unauthorized(OctoKit.BasicError)
            case status402(OctoKit.BasicError)
            case forbidden(OctoKit.BasicError)
            case notFound(OctoKit.BasicError)
            case conflict(OctoKit.BasicError)
        }
    }
}
