// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
@preconcurrency import HTTPHeaders
import TypedAPI
import URLQueryEncoder

extension Paths.CodesOfConduct {
    public func key(_ key: String) -> WithKey {
        WithKey(path: "\(path)/\(key)")
    }

    public struct WithKey {
        /// Path: `/codes_of_conduct/{key}`
        public let path: String

        /// Get a code of conduct
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/codes-of-conduct#get-a-code-of-conduct)
        public var get: Request<OctoKit.CodeOfConduct, GetError> {
            Request(path: path, method: "GET", id: "codes-of-conduct/get-conduct-code")
        }

        public enum GetError: RequestError {
            case notFound(OctoKit.BasicError)
            case notModified
            case unhandled(any Swift.Error)

            public static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
                switch statusCode {
                case 404: return .notFound(try decoder.decode(OctoKit.BasicError.self, from: data))
                case 304: return .notModified
                default: return .unhandled(APIError.unacceptableStatusCode(statusCode))
                }
            }

            public var statusCode: Int? {
                switch self {
                case .notFound: return 404
                case .notModified: return 304
                case .unhandled(let error): return (error as? APIError)?.statusCode
                }
            }

            public var underlyingError: (any Swift.Error)? {
                switch self {
                case .unhandled(let error): return error
                default: return nil
                }
            }
        }
    }
}
