// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
@preconcurrency import NaiveDate

public struct BranchProtection: Codable, Sendable {
    public var url: String?
    public var isEnabled: Bool?
    /// Protected Branch Required Status Check
    public var requiredStatusChecks: ProtectedBranchRequiredStatusCheck?
    /// Protected Branch Admin Enforced
    public var enforceAdmins: ProtectedBranchAdminEnforced?
    /// Protected Branch Pull Request Review
    public var requiredPullRequestReviews: ProtectedBranchPullRequestReview?
    /// Branch Restriction Policy
    public var restrictions: BranchRestrictionPolicy?
    public var requiredLinearHistory: RequiredLinearHistory?
    public var allowForcePushes: AllowForcePushes?
    public var allowDeletions: AllowDeletions?
    public var requiredConversationResolution: RequiredConversationResolution?
    /// Example: "branch/with/protection"
    public var name: String?
    /// Example: "https://api.github.com/repos/owner-79e94e2d36b3fd06a32bb213/AAA_Public_Repo/branches/branch/with/protection/protection"
    public var protectionURL: String?
    public var requiredSignatures: RequiredSignatures?

    public struct RequiredLinearHistory: Codable, Sendable {
        public var isEnabled: Bool?

        public init(isEnabled: Bool? = nil) {
            self.isEnabled = isEnabled
        }

        public init(from decoder: Decoder) throws {
            let values = try decoder.container(keyedBy: StringCodingKey.self)
            self.isEnabled = values.contains("enabled") ? Optional.some(try values.decode(Bool.self, forKey: "enabled")) : nil
        }

        public func encode(to encoder: Encoder) throws {
            var values = encoder.container(keyedBy: StringCodingKey.self)
            try values.encodeIfPresent(isEnabled, forKey: "enabled")
        }
    }

    public struct AllowForcePushes: Codable, Sendable {
        public var isEnabled: Bool?

        public init(isEnabled: Bool? = nil) {
            self.isEnabled = isEnabled
        }

        public init(from decoder: Decoder) throws {
            let values = try decoder.container(keyedBy: StringCodingKey.self)
            self.isEnabled = values.contains("enabled") ? Optional.some(try values.decode(Bool.self, forKey: "enabled")) : nil
        }

        public func encode(to encoder: Encoder) throws {
            var values = encoder.container(keyedBy: StringCodingKey.self)
            try values.encodeIfPresent(isEnabled, forKey: "enabled")
        }
    }

    public struct AllowDeletions: Codable, Sendable {
        public var isEnabled: Bool?

        public init(isEnabled: Bool? = nil) {
            self.isEnabled = isEnabled
        }

        public init(from decoder: Decoder) throws {
            let values = try decoder.container(keyedBy: StringCodingKey.self)
            self.isEnabled = values.contains("enabled") ? Optional.some(try values.decode(Bool.self, forKey: "enabled")) : nil
        }

        public func encode(to encoder: Encoder) throws {
            var values = encoder.container(keyedBy: StringCodingKey.self)
            try values.encodeIfPresent(isEnabled, forKey: "enabled")
        }
    }

    public struct RequiredConversationResolution: Codable, Sendable {
        public var isEnabled: Bool?

        public init(isEnabled: Bool? = nil) {
            self.isEnabled = isEnabled
        }

        public init(from decoder: Decoder) throws {
            let values = try decoder.container(keyedBy: StringCodingKey.self)
            self.isEnabled = values.contains("enabled") ? Optional.some(try values.decode(Bool.self, forKey: "enabled")) : nil
        }

        public func encode(to encoder: Encoder) throws {
            var values = encoder.container(keyedBy: StringCodingKey.self)
            try values.encodeIfPresent(isEnabled, forKey: "enabled")
        }
    }

    public struct RequiredSignatures: Codable, Sendable {
        /// Example: "https://api.github.com/repos/octocat/Hello-World/branches/master/protection/required_signatures"
        public var url: URL
        /// Example: true
        public var isEnabled: Bool

        public init(url: URL, isEnabled: Bool) {
            self.url = url
            self.isEnabled = isEnabled
        }

        public init(from decoder: Decoder) throws {
            let values = try decoder.container(keyedBy: StringCodingKey.self)
            self.url = try values.decode(URL.self, forKey: "url")
            self.isEnabled = try values.decode(Bool.self, forKey: "enabled")
        }

        public func encode(to encoder: Encoder) throws {
            var values = encoder.container(keyedBy: StringCodingKey.self)
            try values.encode(url, forKey: "url")
            try values.encode(isEnabled, forKey: "enabled")
        }
    }

    public init(url: String? = nil, isEnabled: Bool? = nil, requiredStatusChecks: ProtectedBranchRequiredStatusCheck? = nil, enforceAdmins: ProtectedBranchAdminEnforced? = nil, requiredPullRequestReviews: ProtectedBranchPullRequestReview? = nil, restrictions: BranchRestrictionPolicy? = nil, requiredLinearHistory: RequiredLinearHistory? = nil, allowForcePushes: AllowForcePushes? = nil, allowDeletions: AllowDeletions? = nil, requiredConversationResolution: RequiredConversationResolution? = nil, name: String? = nil, protectionURL: String? = nil, requiredSignatures: RequiredSignatures? = nil) {
        self.url = url
        self.isEnabled = isEnabled
        self.requiredStatusChecks = requiredStatusChecks
        self.enforceAdmins = enforceAdmins
        self.requiredPullRequestReviews = requiredPullRequestReviews
        self.restrictions = restrictions
        self.requiredLinearHistory = requiredLinearHistory
        self.allowForcePushes = allowForcePushes
        self.allowDeletions = allowDeletions
        self.requiredConversationResolution = requiredConversationResolution
        self.name = name
        self.protectionURL = protectionURL
        self.requiredSignatures = requiredSignatures
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.url = values.contains("url") ? Optional.some(try values.decode(String.self, forKey: "url")) : nil
        self.isEnabled = values.contains("enabled") ? Optional.some(try values.decode(Bool.self, forKey: "enabled")) : nil
        self.requiredStatusChecks = values.contains("required_status_checks") ? Optional.some(try values.decode(ProtectedBranchRequiredStatusCheck.self, forKey: "required_status_checks")) : nil
        self.enforceAdmins = values.contains("enforce_admins") ? Optional.some(try values.decode(ProtectedBranchAdminEnforced.self, forKey: "enforce_admins")) : nil
        self.requiredPullRequestReviews = values.contains("required_pull_request_reviews") ? Optional.some(try values.decode(ProtectedBranchPullRequestReview.self, forKey: "required_pull_request_reviews")) : nil
        self.restrictions = values.contains("restrictions") ? Optional.some(try values.decode(BranchRestrictionPolicy.self, forKey: "restrictions")) : nil
        self.requiredLinearHistory = values.contains("required_linear_history") ? Optional.some(try values.decode(RequiredLinearHistory.self, forKey: "required_linear_history")) : nil
        self.allowForcePushes = values.contains("allow_force_pushes") ? Optional.some(try values.decode(AllowForcePushes.self, forKey: "allow_force_pushes")) : nil
        self.allowDeletions = values.contains("allow_deletions") ? Optional.some(try values.decode(AllowDeletions.self, forKey: "allow_deletions")) : nil
        self.requiredConversationResolution = values.contains("required_conversation_resolution") ? Optional.some(try values.decode(RequiredConversationResolution.self, forKey: "required_conversation_resolution")) : nil
        self.name = values.contains("name") ? Optional.some(try values.decode(String.self, forKey: "name")) : nil
        self.protectionURL = values.contains("protection_url") ? Optional.some(try values.decode(String.self, forKey: "protection_url")) : nil
        self.requiredSignatures = values.contains("required_signatures") ? Optional.some(try values.decode(RequiredSignatures.self, forKey: "required_signatures")) : nil
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(url, forKey: "url")
        try values.encodeIfPresent(isEnabled, forKey: "enabled")
        try values.encodeIfPresent(requiredStatusChecks, forKey: "required_status_checks")
        try values.encodeIfPresent(enforceAdmins, forKey: "enforce_admins")
        try values.encodeIfPresent(requiredPullRequestReviews, forKey: "required_pull_request_reviews")
        try values.encodeIfPresent(restrictions, forKey: "restrictions")
        try values.encodeIfPresent(requiredLinearHistory, forKey: "required_linear_history")
        try values.encodeIfPresent(allowForcePushes, forKey: "allow_force_pushes")
        try values.encodeIfPresent(allowDeletions, forKey: "allow_deletions")
        try values.encodeIfPresent(requiredConversationResolution, forKey: "required_conversation_resolution")
        try values.encodeIfPresent(name, forKey: "name")
        try values.encodeIfPresent(protectionURL, forKey: "protection_url")
        try values.encodeIfPresent(requiredSignatures, forKey: "required_signatures")
    }
}
