// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
import NaiveDate

/// **Required when the state is dismissed.** The reason for dismissing or closing the alert. Can be one of: `false positive`, `won't fix`, and `used in tests`.
public enum CodeScanningAlertDismissedReason: String, Codable, CaseIterable {
    case falsePositive = "false positive"
    case wontFix = "won't fix"
    case usedInTests = "used in tests"
}
