// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
@preconcurrency import NaiveDate

public struct CodeScanningAlertRuleSummary: Codable, Sendable {
    /// A unique identifier for the rule used to detect the alert.
    public var id: String?
    /// The name of the rule used to detect the alert.
    public var name: String?
    /// The severity of the alert.
    public var severity: Severity?
    /// A short description of the rule used to detect the alert.
    public var description: String?

    /// The severity of the alert.
    public enum Severity: String, Codable, CaseIterable, Sendable {
        case `none`
        case note
        case warning
        case error
    }

    public init(id: String? = nil, name: String? = nil, severity: Severity? = nil, description: String? = nil) {
        self.id = id
        self.name = name
        self.severity = severity
        self.description = description
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decodeIfPresent(String.self, forKey: "id")
        self.name = values.contains("name") ? Optional.some(try values.decode(String.self, forKey: "name")) : nil
        self.severity = try values.decodeIfPresent(Severity.self, forKey: "severity")
        self.description = values.contains("description") ? Optional.some(try values.decode(String.self, forKey: "description")) : nil
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(id, forKey: "id")
        try values.encodeIfPresent(name, forKey: "name")
        try values.encodeIfPresent(severity, forKey: "severity")
        try values.encodeIfPresent(description, forKey: "description")
    }
}
