// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
@preconcurrency import NaiveDate

public struct Event: Codable, Sendable {
    public var id: String
    public var type: String?
    public var actor: Actor
    public var repo: Repo
    /// Actor
    public var org: Actor?
    public var payload: Payload
    public var isPublic: Bool
    public var createdAt: Date?

    public struct Repo: Codable, Sendable {
        public var id: Int
        public var name: String
        public var url: URL

        public init(id: Int, name: String, url: URL) {
            self.id = id
            self.name = name
            self.url = url
        }

        public init(from decoder: Decoder) throws {
            let values = try decoder.container(keyedBy: StringCodingKey.self)
            self.id = try values.decode(Int.self, forKey: "id")
            self.name = try values.decode(String.self, forKey: "name")
            self.url = try values.decode(URL.self, forKey: "url")
        }

        public func encode(to encoder: Encoder) throws {
            var values = encoder.container(keyedBy: StringCodingKey.self)
            try values.encode(id, forKey: "id")
            try values.encode(name, forKey: "name")
            try values.encode(url, forKey: "url")
        }
    }

    public struct Payload: Codable, Sendable {
        public var action: String?
        /// Issues are a great way to keep track of tasks, enhancements, and bugs for your projects.
        public var issue: Issue?
        /// Issue Comment
        ///
        /// Comments provide a way for people to collaborate on an issue.
        public var comment: IssueComment?
        public var pages: [Page]?

        public struct Page: Codable, Sendable {
            public var pageName: String?
            public var title: String?
            public var summary: String?
            public var action: String?
            public var sha: String?
            public var htmlURL: String?

            public init(pageName: String? = nil, title: String? = nil, summary: String? = nil, action: String? = nil, sha: String? = nil, htmlURL: String? = nil) {
                self.pageName = pageName
                self.title = title
                self.summary = summary
                self.action = action
                self.sha = sha
                self.htmlURL = htmlURL
            }

            public init(from decoder: Decoder) throws {
                let values = try decoder.container(keyedBy: StringCodingKey.self)
                self.pageName = values.contains("page_name") ? Optional.some(try values.decode(String.self, forKey: "page_name")) : nil
                self.title = values.contains("title") ? Optional.some(try values.decode(String.self, forKey: "title")) : nil
                self.summary = try values.decodeIfPresent(String.self, forKey: "summary")
                self.action = values.contains("action") ? Optional.some(try values.decode(String.self, forKey: "action")) : nil
                self.sha = values.contains("sha") ? Optional.some(try values.decode(String.self, forKey: "sha")) : nil
                self.htmlURL = values.contains("html_url") ? Optional.some(try values.decode(String.self, forKey: "html_url")) : nil
            }

            public func encode(to encoder: Encoder) throws {
                var values = encoder.container(keyedBy: StringCodingKey.self)
                try values.encodeIfPresent(pageName, forKey: "page_name")
                try values.encodeIfPresent(title, forKey: "title")
                try values.encodeIfPresent(summary, forKey: "summary")
                try values.encodeIfPresent(action, forKey: "action")
                try values.encodeIfPresent(sha, forKey: "sha")
                try values.encodeIfPresent(htmlURL, forKey: "html_url")
            }
        }

        public init(action: String? = nil, issue: Issue? = nil, comment: IssueComment? = nil, pages: [Page]? = nil) {
            self.action = action
            self.issue = issue
            self.comment = comment
            self.pages = pages
        }

        public init(from decoder: Decoder) throws {
            let values = try decoder.container(keyedBy: StringCodingKey.self)
            self.action = values.contains("action") ? Optional.some(try values.decode(String.self, forKey: "action")) : nil
            self.issue = values.contains("issue") ? Optional.some(try values.decode(Issue.self, forKey: "issue")) : nil
            self.comment = values.contains("comment") ? Optional.some(try values.decode(IssueComment.self, forKey: "comment")) : nil
            self.pages = values.contains("pages") ? Optional.some(try values.decode([Page].self, forKey: "pages")) : nil
        }

        public func encode(to encoder: Encoder) throws {
            var values = encoder.container(keyedBy: StringCodingKey.self)
            try values.encodeIfPresent(action, forKey: "action")
            try values.encodeIfPresent(issue, forKey: "issue")
            try values.encodeIfPresent(comment, forKey: "comment")
            try values.encodeIfPresent(pages, forKey: "pages")
        }
    }

    public init(id: String, type: String? = nil, actor: Actor, repo: Repo, org: Actor? = nil, payload: Payload, isPublic: Bool, createdAt: Date? = nil) {
        self.id = id
        self.type = type
        self.actor = actor
        self.repo = repo
        self.org = org
        self.payload = payload
        self.isPublic = isPublic
        self.createdAt = createdAt
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decode(String.self, forKey: "id")
        self.type = try values.decode(String?.self, forKey: "type")
        self.actor = try values.decode(Actor.self, forKey: "actor")
        self.repo = try values.decode(Repo.self, forKey: "repo")
        self.org = values.contains("org") ? Optional.some(try values.decode(Actor.self, forKey: "org")) : nil
        self.payload = try values.decode(Payload.self, forKey: "payload")
        self.isPublic = try values.decode(Bool.self, forKey: "public")
        self.createdAt = try values.decode(Date?.self, forKey: "created_at")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(id, forKey: "id")
        try values.encode(type, forKey: "type")
        try values.encode(actor, forKey: "actor")
        try values.encode(repo, forKey: "repo")
        try values.encodeIfPresent(org, forKey: "org")
        try values.encode(payload, forKey: "payload")
        try values.encode(isPublic, forKey: "public")
        try values.encode(createdAt, forKey: "created_at")
    }
}
