// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
@preconcurrency import NaiveDate

public struct FileCommit: Codable, Sendable {
    public var content: Content?
    public var commit: Commit

    public struct Content: Codable, Sendable {
        public var name: String?
        public var path: String?
        public var sha: String?
        public var size: Int?
        public var url: String?
        public var htmlURL: String?
        public var gitURL: String?
        public var downloadURL: String?
        public var type: String?
        public var links: Links?

        public struct Links: Codable, Sendable {
            public var this: String?
            public var git: String?
            public var html: String?

            public init(this: String? = nil, git: String? = nil, html: String? = nil) {
                self.this = this
                self.git = git
                self.html = html
            }

            public init(from decoder: Decoder) throws {
                let values = try decoder.container(keyedBy: StringCodingKey.self)
                self.this = values.contains("self") ? Optional.some(try values.decode(String.self, forKey: "self")) : nil
                self.git = values.contains("git") ? Optional.some(try values.decode(String.self, forKey: "git")) : nil
                self.html = values.contains("html") ? Optional.some(try values.decode(String.self, forKey: "html")) : nil
            }

            public func encode(to encoder: Encoder) throws {
                var values = encoder.container(keyedBy: StringCodingKey.self)
                try values.encodeIfPresent(this, forKey: "self")
                try values.encodeIfPresent(git, forKey: "git")
                try values.encodeIfPresent(html, forKey: "html")
            }
        }

        public init(name: String? = nil, path: String? = nil, sha: String? = nil, size: Int? = nil, url: String? = nil, htmlURL: String? = nil, gitURL: String? = nil, downloadURL: String? = nil, type: String? = nil, links: Links? = nil) {
            self.name = name
            self.path = path
            self.sha = sha
            self.size = size
            self.url = url
            self.htmlURL = htmlURL
            self.gitURL = gitURL
            self.downloadURL = downloadURL
            self.type = type
            self.links = links
        }

        public init(from decoder: Decoder) throws {
            let values = try decoder.container(keyedBy: StringCodingKey.self)
            self.name = values.contains("name") ? Optional.some(try values.decode(String.self, forKey: "name")) : nil
            self.path = values.contains("path") ? Optional.some(try values.decode(String.self, forKey: "path")) : nil
            self.sha = values.contains("sha") ? Optional.some(try values.decode(String.self, forKey: "sha")) : nil
            self.size = values.contains("size") ? Optional.some(try values.decode(Int.self, forKey: "size")) : nil
            self.url = values.contains("url") ? Optional.some(try values.decode(String.self, forKey: "url")) : nil
            self.htmlURL = values.contains("html_url") ? Optional.some(try values.decode(String.self, forKey: "html_url")) : nil
            self.gitURL = values.contains("git_url") ? Optional.some(try values.decode(String.self, forKey: "git_url")) : nil
            self.downloadURL = values.contains("download_url") ? Optional.some(try values.decode(String.self, forKey: "download_url")) : nil
            self.type = values.contains("type") ? Optional.some(try values.decode(String.self, forKey: "type")) : nil
            self.links = values.contains("_links") ? Optional.some(try values.decode(Links.self, forKey: "_links")) : nil
        }

        public func encode(to encoder: Encoder) throws {
            var values = encoder.container(keyedBy: StringCodingKey.self)
            try values.encodeIfPresent(name, forKey: "name")
            try values.encodeIfPresent(path, forKey: "path")
            try values.encodeIfPresent(sha, forKey: "sha")
            try values.encodeIfPresent(size, forKey: "size")
            try values.encodeIfPresent(url, forKey: "url")
            try values.encodeIfPresent(htmlURL, forKey: "html_url")
            try values.encodeIfPresent(gitURL, forKey: "git_url")
            try values.encodeIfPresent(downloadURL, forKey: "download_url")
            try values.encodeIfPresent(type, forKey: "type")
            try values.encodeIfPresent(links, forKey: "_links")
        }
    }

    public struct Commit: Codable, Sendable {
        public var sha: String?
        public var nodeID: String?
        public var url: String?
        public var htmlURL: String?
        public var author: Author?
        public var committer: Committer?
        public var message: String?
        public var tree: Tree?
        public var parents: [Parent]?
        public var verification: Verification?

        public struct Author: Codable, Sendable {
            public var date: String?
            public var name: String?
            public var email: String?

            public init(date: String? = nil, name: String? = nil, email: String? = nil) {
                self.date = date
                self.name = name
                self.email = email
            }

            public init(from decoder: Decoder) throws {
                let values = try decoder.container(keyedBy: StringCodingKey.self)
                self.date = values.contains("date") ? Optional.some(try values.decode(String.self, forKey: "date")) : nil
                self.name = values.contains("name") ? Optional.some(try values.decode(String.self, forKey: "name")) : nil
                self.email = values.contains("email") ? Optional.some(try values.decode(String.self, forKey: "email")) : nil
            }

            public func encode(to encoder: Encoder) throws {
                var values = encoder.container(keyedBy: StringCodingKey.self)
                try values.encodeIfPresent(date, forKey: "date")
                try values.encodeIfPresent(name, forKey: "name")
                try values.encodeIfPresent(email, forKey: "email")
            }
        }

        public struct Committer: Codable, Sendable {
            public var date: String?
            public var name: String?
            public var email: String?

            public init(date: String? = nil, name: String? = nil, email: String? = nil) {
                self.date = date
                self.name = name
                self.email = email
            }

            public init(from decoder: Decoder) throws {
                let values = try decoder.container(keyedBy: StringCodingKey.self)
                self.date = values.contains("date") ? Optional.some(try values.decode(String.self, forKey: "date")) : nil
                self.name = values.contains("name") ? Optional.some(try values.decode(String.self, forKey: "name")) : nil
                self.email = values.contains("email") ? Optional.some(try values.decode(String.self, forKey: "email")) : nil
            }

            public func encode(to encoder: Encoder) throws {
                var values = encoder.container(keyedBy: StringCodingKey.self)
                try values.encodeIfPresent(date, forKey: "date")
                try values.encodeIfPresent(name, forKey: "name")
                try values.encodeIfPresent(email, forKey: "email")
            }
        }

        public struct Tree: Codable, Sendable {
            public var url: String?
            public var sha: String?

            public init(url: String? = nil, sha: String? = nil) {
                self.url = url
                self.sha = sha
            }

            public init(from decoder: Decoder) throws {
                let values = try decoder.container(keyedBy: StringCodingKey.self)
                self.url = values.contains("url") ? Optional.some(try values.decode(String.self, forKey: "url")) : nil
                self.sha = values.contains("sha") ? Optional.some(try values.decode(String.self, forKey: "sha")) : nil
            }

            public func encode(to encoder: Encoder) throws {
                var values = encoder.container(keyedBy: StringCodingKey.self)
                try values.encodeIfPresent(url, forKey: "url")
                try values.encodeIfPresent(sha, forKey: "sha")
            }
        }

        public struct Parent: Codable, Sendable {
            public var url: String?
            public var htmlURL: String?
            public var sha: String?

            public init(url: String? = nil, htmlURL: String? = nil, sha: String? = nil) {
                self.url = url
                self.htmlURL = htmlURL
                self.sha = sha
            }

            public init(from decoder: Decoder) throws {
                let values = try decoder.container(keyedBy: StringCodingKey.self)
                self.url = values.contains("url") ? Optional.some(try values.decode(String.self, forKey: "url")) : nil
                self.htmlURL = values.contains("html_url") ? Optional.some(try values.decode(String.self, forKey: "html_url")) : nil
                self.sha = values.contains("sha") ? Optional.some(try values.decode(String.self, forKey: "sha")) : nil
            }

            public func encode(to encoder: Encoder) throws {
                var values = encoder.container(keyedBy: StringCodingKey.self)
                try values.encodeIfPresent(url, forKey: "url")
                try values.encodeIfPresent(htmlURL, forKey: "html_url")
                try values.encodeIfPresent(sha, forKey: "sha")
            }
        }

        public struct Verification: Codable, Sendable {
            public var isVerified: Bool?
            public var reason: String?
            public var signature: String?
            public var payload: String?

            public init(isVerified: Bool? = nil, reason: String? = nil, signature: String? = nil, payload: String? = nil) {
                self.isVerified = isVerified
                self.reason = reason
                self.signature = signature
                self.payload = payload
            }

            public init(from decoder: Decoder) throws {
                let values = try decoder.container(keyedBy: StringCodingKey.self)
                self.isVerified = values.contains("verified") ? Optional.some(try values.decode(Bool.self, forKey: "verified")) : nil
                self.reason = values.contains("reason") ? Optional.some(try values.decode(String.self, forKey: "reason")) : nil
                self.signature = try values.decodeIfPresent(String.self, forKey: "signature")
                self.payload = try values.decodeIfPresent(String.self, forKey: "payload")
            }

            public func encode(to encoder: Encoder) throws {
                var values = encoder.container(keyedBy: StringCodingKey.self)
                try values.encodeIfPresent(isVerified, forKey: "verified")
                try values.encodeIfPresent(reason, forKey: "reason")
                try values.encodeIfPresent(signature, forKey: "signature")
                try values.encodeIfPresent(payload, forKey: "payload")
            }
        }

        public init(sha: String? = nil, nodeID: String? = nil, url: String? = nil, htmlURL: String? = nil, author: Author? = nil, committer: Committer? = nil, message: String? = nil, tree: Tree? = nil, parents: [Parent]? = nil, verification: Verification? = nil) {
            self.sha = sha
            self.nodeID = nodeID
            self.url = url
            self.htmlURL = htmlURL
            self.author = author
            self.committer = committer
            self.message = message
            self.tree = tree
            self.parents = parents
            self.verification = verification
        }

        public init(from decoder: Decoder) throws {
            let values = try decoder.container(keyedBy: StringCodingKey.self)
            self.sha = values.contains("sha") ? Optional.some(try values.decode(String.self, forKey: "sha")) : nil
            self.nodeID = values.contains("node_id") ? Optional.some(try values.decode(String.self, forKey: "node_id")) : nil
            self.url = values.contains("url") ? Optional.some(try values.decode(String.self, forKey: "url")) : nil
            self.htmlURL = values.contains("html_url") ? Optional.some(try values.decode(String.self, forKey: "html_url")) : nil
            self.author = values.contains("author") ? Optional.some(try values.decode(Author.self, forKey: "author")) : nil
            self.committer = values.contains("committer") ? Optional.some(try values.decode(Committer.self, forKey: "committer")) : nil
            self.message = values.contains("message") ? Optional.some(try values.decode(String.self, forKey: "message")) : nil
            self.tree = values.contains("tree") ? Optional.some(try values.decode(Tree.self, forKey: "tree")) : nil
            self.parents = values.contains("parents") ? Optional.some(try values.decode([Parent].self, forKey: "parents")) : nil
            self.verification = values.contains("verification") ? Optional.some(try values.decode(Verification.self, forKey: "verification")) : nil
        }

        public func encode(to encoder: Encoder) throws {
            var values = encoder.container(keyedBy: StringCodingKey.self)
            try values.encodeIfPresent(sha, forKey: "sha")
            try values.encodeIfPresent(nodeID, forKey: "node_id")
            try values.encodeIfPresent(url, forKey: "url")
            try values.encodeIfPresent(htmlURL, forKey: "html_url")
            try values.encodeIfPresent(author, forKey: "author")
            try values.encodeIfPresent(committer, forKey: "committer")
            try values.encodeIfPresent(message, forKey: "message")
            try values.encodeIfPresent(tree, forKey: "tree")
            try values.encodeIfPresent(parents, forKey: "parents")
            try values.encodeIfPresent(verification, forKey: "verification")
        }
    }

    public init(content: Content? = nil, commit: Commit) {
        self.content = content
        self.commit = commit
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.content = try values.decode(Content?.self, forKey: "content")
        self.commit = try values.decode(Commit.self, forKey: "commit")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(content, forKey: "content")
        try values.encode(commit, forKey: "commit")
    }
}
