// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
@preconcurrency import NaiveDate

/// Metaproperties for Git author/committer information.
public struct GitUser: Codable, Sendable {
    /// Example: "Chris Wanstrath"
    public var name: String?
    /// Example: "chris@ozmm.org"
    public var email: String?
    /// Example: "2007-10-29T02:42:39.000-07:00"
    public var date: String?

    public init(name: String? = nil, email: String? = nil, date: String? = nil) {
        self.name = name
        self.email = email
        self.date = date
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.name = values.contains("name") ? Optional.some(try values.decode(String.self, forKey: "name")) : nil
        self.email = values.contains("email") ? Optional.some(try values.decode(String.self, forKey: "email")) : nil
        self.date = values.contains("date") ? Optional.some(try values.decode(String.self, forKey: "date")) : nil
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(name, forKey: "name")
        try values.encodeIfPresent(email, forKey: "email")
        try values.encodeIfPresent(date, forKey: "date")
    }
}
