// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
@preconcurrency import NaiveDate

public struct IssueEventLabel: Codable, Sendable {
    public var name: String?
    public var color: String?

    public init(name: String? = nil, color: String? = nil) {
        self.name = name
        self.color = color
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.name = try values.decode(String?.self, forKey: "name")
        self.color = try values.decode(String?.self, forKey: "color")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(name, forKey: "name")
        try values.encode(color, forKey: "color")
    }
}
