// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
import NaiveDate

public struct IssueEventRename: Codable, Sendable {
    public var from: String
    public var to: String

    public init(from: String, to: String) {
        self.from = from
        self.to = to
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.from = try values.decode(String.self, forKey: "from")
        self.to = try values.decode(String.self, forKey: "to")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(from, forKey: "from")
        try values.encode(to, forKey: "to")
    }
}
