// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
import NaiveDate

public struct ProjectCollaboratorPermission: Codable, Sendable {
    public var permission: String
    /// Simple User
    public var user: SimpleUser?

    public init(permission: String, user: SimpleUser? = nil) {
        self.permission = permission
        self.user = user
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.permission = try values.decode(String.self, forKey: "permission")
        self.user = try values.decodeIfPresent(SimpleUser.self, forKey: "user")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(permission, forKey: "permission")
        try values.encodeIfPresent(user, forKey: "user")
    }
}
