// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
@preconcurrency import NaiveDate

public struct RateLimitOverview: Codable, Sendable {
    public var resources: Resources
    /// Rate Limit
    public var rate: RateLimit

    public struct Resources: Codable, Sendable {
        /// Rate Limit
        public var core: RateLimit
        /// Rate Limit
        public var graphql: RateLimit?
        /// Rate Limit
        public var search: RateLimit
        /// Rate Limit
        public var sourceImport: RateLimit?
        /// Rate Limit
        public var integrationManifest: RateLimit?
        /// Rate Limit
        public var codeScanningUpload: RateLimit?
        /// Rate Limit
        public var actionsRunnerRegistration: RateLimit?
        /// Rate Limit
        public var scim: RateLimit?

        public init(core: RateLimit, graphql: RateLimit? = nil, search: RateLimit, sourceImport: RateLimit? = nil, integrationManifest: RateLimit? = nil, codeScanningUpload: RateLimit? = nil, actionsRunnerRegistration: RateLimit? = nil, scim: RateLimit? = nil) {
            self.core = core
            self.graphql = graphql
            self.search = search
            self.sourceImport = sourceImport
            self.integrationManifest = integrationManifest
            self.codeScanningUpload = codeScanningUpload
            self.actionsRunnerRegistration = actionsRunnerRegistration
            self.scim = scim
        }

        public init(from decoder: Decoder) throws {
            let values = try decoder.container(keyedBy: StringCodingKey.self)
            self.core = try values.decode(RateLimit.self, forKey: "core")
            self.graphql = values.contains("graphql") ? Optional.some(try values.decode(RateLimit.self, forKey: "graphql")) : nil
            self.search = try values.decode(RateLimit.self, forKey: "search")
            self.sourceImport = values.contains("source_import") ? Optional.some(try values.decode(RateLimit.self, forKey: "source_import")) : nil
            self.integrationManifest = values.contains("integration_manifest") ? Optional.some(try values.decode(RateLimit.self, forKey: "integration_manifest")) : nil
            self.codeScanningUpload = values.contains("code_scanning_upload") ? Optional.some(try values.decode(RateLimit.self, forKey: "code_scanning_upload")) : nil
            self.actionsRunnerRegistration = values.contains("actions_runner_registration") ? Optional.some(try values.decode(RateLimit.self, forKey: "actions_runner_registration")) : nil
            self.scim = values.contains("scim") ? Optional.some(try values.decode(RateLimit.self, forKey: "scim")) : nil
        }

        public func encode(to encoder: Encoder) throws {
            var values = encoder.container(keyedBy: StringCodingKey.self)
            try values.encode(core, forKey: "core")
            try values.encodeIfPresent(graphql, forKey: "graphql")
            try values.encode(search, forKey: "search")
            try values.encodeIfPresent(sourceImport, forKey: "source_import")
            try values.encodeIfPresent(integrationManifest, forKey: "integration_manifest")
            try values.encodeIfPresent(codeScanningUpload, forKey: "code_scanning_upload")
            try values.encodeIfPresent(actionsRunnerRegistration, forKey: "actions_runner_registration")
            try values.encodeIfPresent(scim, forKey: "scim")
        }
    }

    public init(resources: Resources, rate: RateLimit) {
        self.resources = resources
        self.rate = rate
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.resources = try values.decode(Resources.self, forKey: "resources")
        self.rate = try values.decode(RateLimit.self, forKey: "rate")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(resources, forKey: "resources")
        try values.encode(rate, forKey: "rate")
    }
}
