// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
@preconcurrency import NaiveDate

public struct WorkflowUsage: Codable, Sendable {
    public var billable: Billable

    public struct Billable: Codable, Sendable {
        public var ubuntu: Ubuntu?
        public var macos: Macos?
        public var windows: Windows?

        public struct Ubuntu: Codable, Sendable {
            public var totalMs: Int?

            public init(totalMs: Int? = nil) {
                self.totalMs = totalMs
            }

            public init(from decoder: Decoder) throws {
                let values = try decoder.container(keyedBy: StringCodingKey.self)
                self.totalMs = values.contains("total_ms") ? Optional.some(try values.decode(Int.self, forKey: "total_ms")) : nil
            }

            public func encode(to encoder: Encoder) throws {
                var values = encoder.container(keyedBy: StringCodingKey.self)
                try values.encodeIfPresent(totalMs, forKey: "total_ms")
            }
        }

        public struct Macos: Codable, Sendable {
            public var totalMs: Int?

            public init(totalMs: Int? = nil) {
                self.totalMs = totalMs
            }

            public init(from decoder: Decoder) throws {
                let values = try decoder.container(keyedBy: StringCodingKey.self)
                self.totalMs = values.contains("total_ms") ? Optional.some(try values.decode(Int.self, forKey: "total_ms")) : nil
            }

            public func encode(to encoder: Encoder) throws {
                var values = encoder.container(keyedBy: StringCodingKey.self)
                try values.encodeIfPresent(totalMs, forKey: "total_ms")
            }
        }

        public struct Windows: Codable, Sendable {
            public var totalMs: Int?

            public init(totalMs: Int? = nil) {
                self.totalMs = totalMs
            }

            public init(from decoder: Decoder) throws {
                let values = try decoder.container(keyedBy: StringCodingKey.self)
                self.totalMs = values.contains("total_ms") ? Optional.some(try values.decode(Int.self, forKey: "total_ms")) : nil
            }

            public func encode(to encoder: Encoder) throws {
                var values = encoder.container(keyedBy: StringCodingKey.self)
                try values.encodeIfPresent(totalMs, forKey: "total_ms")
            }
        }

        public init(ubuntu: Ubuntu? = nil, macos: Macos? = nil, windows: Windows? = nil) {
            self.ubuntu = ubuntu
            self.macos = macos
            self.windows = windows
        }

        public init(from decoder: Decoder) throws {
            let values = try decoder.container(keyedBy: StringCodingKey.self)
            self.ubuntu = values.contains("UBUNTU") ? Optional.some(try values.decode(Ubuntu.self, forKey: "UBUNTU")) : nil
            self.macos = values.contains("MACOS") ? Optional.some(try values.decode(Macos.self, forKey: "MACOS")) : nil
            self.windows = values.contains("WINDOWS") ? Optional.some(try values.decode(Windows.self, forKey: "WINDOWS")) : nil
        }

        public func encode(to encoder: Encoder) throws {
            var values = encoder.container(keyedBy: StringCodingKey.self)
            try values.encodeIfPresent(ubuntu, forKey: "UBUNTU")
            try values.encodeIfPresent(macos, forKey: "MACOS")
            try values.encodeIfPresent(windows, forKey: "WINDOWS")
        }
    }

    public init(billable: Billable) {
        self.billable = billable
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.billable = try values.decode(Billable.self, forKey: "billable")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(billable, forKey: "billable")
    }
}
