// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
@preconcurrency import NaiveDate

/// Model for testing model name starting with number
struct __200Response: Codable, Sendable {
    var name: Int32?
    var `class`: String?

    init(name: Int32? = nil, `class`: String? = nil) {
        self.name = name
        self.class = `class`
    }

    init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.name = values.contains("name") ? Optional.some(try values.decode(Int32.self, forKey: "name")) : nil
        self.class = values.contains("class") ? Optional.some(try values.decode(String.self, forKey: "class")) : nil
    }

    func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(name, forKey: "name")
        try values.encodeIfPresent(`class`, forKey: "class")
    }
}
