// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
@preconcurrency import NaiveDate

struct APIResponse: Codable, Sendable {
    var code: Int32?
    var type: String?
    var message: String?

    init(code: Int32? = nil, type: String? = nil, message: String? = nil) {
        self.code = code
        self.type = type
        self.message = message
    }

    init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.code = values.contains("code") ? Optional.some(try values.decode(Int32.self, forKey: "code")) : nil
        self.type = values.contains("type") ? Optional.some(try values.decode(String.self, forKey: "type")) : nil
        self.message = values.contains("message") ? Optional.some(try values.decode(String.self, forKey: "message")) : nil
    }

    func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(code, forKey: "code")
        try values.encodeIfPresent(type, forKey: "type")
        try values.encodeIfPresent(message, forKey: "message")
    }
}
