// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
@preconcurrency import NaiveDate

struct ArrayOfArrayOfNumberOnly: Codable, Sendable {
    var arrayArrayNumber: [[Double]]?

    init(arrayArrayNumber: [[Double]]? = nil) {
        self.arrayArrayNumber = arrayArrayNumber
    }

    init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.arrayArrayNumber = values.contains("ArrayArrayNumber") ? Optional.some(try values.decode([[Double]].self, forKey: "ArrayArrayNumber")) : nil
    }

    func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(arrayArrayNumber, forKey: "ArrayArrayNumber")
    }
}
