// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
@preconcurrency import NaiveDate

struct EnumTest: Codable, Sendable {
    var enumString: EnumString?
    var enumInteger: Int32?
    var enumNumber: Double?
    var outerEnum: OuterEnum?

    enum EnumString: String, Codable, CaseIterable, Sendable {
        case upper = "UPPER"
        case lower
        case empty = ""
    }

    init(enumString: EnumString? = nil, enumInteger: Int32? = nil, enumNumber: Double? = nil, outerEnum: OuterEnum? = nil) {
        self.enumString = enumString
        self.enumInteger = enumInteger
        self.enumNumber = enumNumber
        self.outerEnum = outerEnum
    }

    init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.enumString = values.contains("enum_string") ? Optional.some(try values.decode(EnumString.self, forKey: "enum_string")) : nil
        self.enumInteger = values.contains("enum_integer") ? Optional.some(try values.decode(Int32.self, forKey: "enum_integer")) : nil
        self.enumNumber = values.contains("enum_number") ? Optional.some(try values.decode(Double.self, forKey: "enum_number")) : nil
        self.outerEnum = values.contains("outerEnum") ? Optional.some(try values.decode(OuterEnum.self, forKey: "outerEnum")) : nil
    }

    func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(enumString, forKey: "enum_string")
        try values.encodeIfPresent(enumInteger, forKey: "enum_integer")
        try values.encodeIfPresent(enumNumber, forKey: "enum_number")
        try values.encodeIfPresent(outerEnum, forKey: "outerEnum")
    }
}
