// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
import TypedAPI

extension Paths.Collections.WithID {
    public var recipes: Recipes {
        Recipes(path: path + "/recipes")
    }

    public struct Recipes {
        /// Path: `/api/collections/{id}/recipes`
        public let path: String

        /// Find Recipes in a Collection
        ///
        /// Returns an ordered array of Recipe models in the given Collection.
        public var get: Request<[cookpad.Recipe], GetError> {
            Request(path: path, method: "GET", id: "getCollectionRecipes")
        }

        public enum GetError: RequestError {
            case notFound
            case unhandled(any Swift.Error)

            public static func decode(statusCode: Int, data: Data, decoder: JSONDecoder) throws -> Self {
                switch statusCode {
                case 404: return .notFound
                default: return .unhandled(APIError.unacceptableStatusCode(statusCode))
                }
            }

            public var underlyingError: (any Swift.Error)? {
                switch self {
                case .unhandled(let error): return error
                default: return nil
                }
            }
        }
    }
}
