// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
import NaiveDate

/// Model for testing model name starting with number
public struct __200Response: Codable, Sendable {
    public var name: Int32?
    public var `class`: String?

    public init(name: Int32? = nil, `class`: String? = nil) {
        self.name = name
        self.class = `class`
    }

    private enum CodingKeys: String, CodingKey {
        case name
        case `class`
    }
}
