// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
@preconcurrency import NaiveDate

/// Model for testing model with "_class" property
public struct ClassModel: Codable, Sendable {
    public var `class`: String?

    public init(`class`: String? = nil) {
        self.class = `class`
    }

    private enum CodingKeys: String, CodingKey {
        case `class` = "_class"
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: CodingKeys.self)
        self.class = values.contains(.`class`) ? Optional.some(try values.decode(String.self, forKey: .`class`)) : nil
    }
}
