// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
import NaiveDate

public struct Client: Codable, Sendable {
    public var client: String?

    public init(client: String? = nil) {
        self.client = client
    }
}
