// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
import NaiveDate

public struct ContainerA: Codable, Sendable {
    public var child: Child?
    public var refChild: AnyJSON

    public struct Child: Codable, Sendable {
        public var `enum`: Enum
        public var renameMe: String
        public var child: Child

        public enum Enum: String, Codable, CaseIterable {
            case a
            case b
        }

        public struct Child: Codable, Sendable {
            public var `enum`: Enum
            public var renameMe: String

            public enum Enum: String, Codable, CaseIterable {
                case a
                case b
            }

            public init(`enum`: Enum, renameMe: String) {
                self.enum = `enum`
                self.renameMe = renameMe
            }

            private enum CodingKeys: String, CodingKey {
                case `enum`
                case renameMe = "rename-me"
            }
        }

        public init(`enum`: Enum, renameMe: String, child: Child) {
            self.enum = `enum`
            self.renameMe = renameMe
            self.child = child
        }

        private enum CodingKeys: String, CodingKey {
            case `enum`
            case renameMe = "rename-me"
            case child
        }
    }

    public init(child: Child? = nil, refChild: AnyJSON) {
        self.child = child
        self.refChild = refChild
    }
}
