// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
import NaiveDate

public struct ContainerC: Codable, Sendable {
    public var child: Child

    public struct Child: Codable, Sendable {
        public var `enum`: Enum
        public var renameMe: String

        public enum Enum: String, Codable, CaseIterable {
            case a
            case b
        }

        public init(`enum`: Enum, renameMe: String) {
            self.enum = `enum`
            self.renameMe = renameMe
        }

        private enum CodingKeys: String, CodingKey {
            case `enum`
            case renameMe = "rename-me"
        }
    }

    public init(child: Child) {
        self.child = child
    }
}
