// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
import NaiveDate

public struct List: Codable, Sendable {
    public var _123List: String?

    public init(_123List: String? = nil) {
        self._123List = _123List
    }

    private enum CodingKeys: String, CodingKey {
        case _123List = "123-list"
    }
}
