// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
@preconcurrency import NaiveDate

public struct MapTest: Codable, Sendable {
    public var mapMapOfString: [String: [String: String]]?
    public var mapOfEnumString: [String: MapOfEnumStringItem]?

    public enum MapOfEnumStringItem: String, Codable, CaseIterable, Sendable {
        case upper = "UPPER"
        case lower
    }

    public init(mapMapOfString: [String: [String: String]]? = nil, mapOfEnumString: [String: MapOfEnumStringItem]? = nil) {
        self.mapMapOfString = mapMapOfString
        self.mapOfEnumString = mapOfEnumString
    }

    private enum CodingKeys: String, CodingKey {
        case mapMapOfString = "map_map_of_string"
        case mapOfEnumString = "map_of_enum_string"
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: CodingKeys.self)
        self.mapMapOfString = values.contains(.mapMapOfString) ? Optional.some(try values.decode([String: [String: String]].self, forKey: .mapMapOfString)) : nil
        self.mapOfEnumString = values.contains(.mapOfEnumString) ? Optional.some(try values.decode([String: MapOfEnumStringItem].self, forKey: .mapOfEnumString)) : nil
    }
}
