// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
@preconcurrency import NaiveDate

public struct ReadOnlyFirst: Codable, Sendable {
    public var bar: String?
    public var baz: String?

    public init(bar: String? = nil, baz: String? = nil) {
        self.bar = bar
        self.baz = baz
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: CodingKeys.self)
        self.bar = values.contains(.bar) ? Optional.some(try values.decode(String.self, forKey: .bar)) : nil
        self.baz = values.contains(.baz) ? Optional.some(try values.decode(String.self, forKey: .baz)) : nil
    }
}
