// Generated by Create API
// https://github.com/jfd02/swift-typed-api

import Foundation
@preconcurrency import NaiveDate

public struct User: Codable, Sendable {
    public var id: Int64?
    public var username: String?
    public var firstName: String?
    public var lastName: String?
    public var email: String?
    public var password: String?
    public var phone: String?
    /// User Status
    public var userStatus: Int32?

    public init(id: Int64? = nil, username: String? = nil, firstName: String? = nil, lastName: String? = nil, email: String? = nil, password: String? = nil, phone: String? = nil, userStatus: Int32? = nil) {
        self.id = id
        self.username = username
        self.firstName = firstName
        self.lastName = lastName
        self.email = email
        self.password = password
        self.phone = phone
        self.userStatus = userStatus
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: CodingKeys.self)
        self.id = values.contains(.id) ? Optional.some(try values.decode(Int64.self, forKey: .id)) : nil
        self.username = values.contains(.username) ? Optional.some(try values.decode(String.self, forKey: .username)) : nil
        self.firstName = values.contains(.firstName) ? Optional.some(try values.decode(String.self, forKey: .firstName)) : nil
        self.lastName = values.contains(.lastName) ? Optional.some(try values.decode(String.self, forKey: .lastName)) : nil
        self.email = values.contains(.email) ? Optional.some(try values.decode(String.self, forKey: .email)) : nil
        self.password = values.contains(.password) ? Optional.some(try values.decode(String.self, forKey: .password)) : nil
        self.phone = values.contains(.phone) ? Optional.some(try values.decode(String.self, forKey: .phone)) : nil
        self.userStatus = values.contains(.userStatus) ? Optional.some(try values.decode(Int32.self, forKey: .userStatus)) : nil
    }
}
